CREATE TABLE [dbo].[p_TitleObject] (
    [TitleObject_ID]                     UNIQUEIDENTIFIER CONSTRAINT [DF_TitleObject_ID] DEFAULT (newsequentialid()) NOT NULL,
    [RowStatus]                          INT              NOT NULL,
    [Insert_DTS]                         DATETIME2 (7)    NOT NULL,
    [Update_DTS]                         DATETIME2 (7)    NOT NULL,
    [Created_User_ID]                    UNIQUEIDENTIFIER NOT NULL,
    [Modified_User_ID]                   UNIQUEIDENTIFIER NOT NULL,
    [TitleObject_Code]                   NVARCHAR (255)   NOT NULL,
    [Parent_ID]                          UNIQUEIDENTIFIER NULL,
    [Structure]                          INT              CONSTRAINT [DF_Structure] DEFAULT ((1)) NOT NULL,
    [Description_Eng]                    NVARCHAR (300)   NULL,
    [Description_Rus]                    NVARCHAR (400)   NULL,
    [Phase_Name]                         NVARCHAR (100)   NULL,
    [ReportColor]                        NVARCHAR (50)    NULL,
    [ReportOrder]                        INT              NULL,
    [GLB_Weight]                         FLOAT (53)       NULL,
    [Row_Status]                         INT              NULL,
    [Book1_Pct]                          FLOAT (53)       NULL,
    [Book1_Weight]                       FLOAT (53)       NULL,
    [Book2_Pct]                          FLOAT (53)       NULL,
    [Book2_Weight]                       FLOAT (53)       NULL,
    [Book3_Pct]                          FLOAT (53)       NULL,
    [Book3_Weight]                       FLOAT (53)       NULL,
    [Book4_Weight]                       FLOAT (53)       NULL,
    [TitleObject_for_ABDFinalSet]        NVARCHAR (100)   NULL,
    [Book1_Documents_Total]              FLOAT (53)       NULL,
    [Book1_Documents_received]           FLOAT (53)       NULL,
    [Book1_Progress]                     FLOAT (53)       NULL,
    [Book1_Documents_transmitted_to_CPY] FLOAT (53)       NULL,
    [StageOfConstr]                      NVARCHAR (10)    NULL,
    CONSTRAINT [PK_p_TitleObject] PRIMARY KEY CLUSTERED ([TitleObject_ID] ASC),
    CONSTRAINT [FK_p_TitleObject_Created_User_ID_p_AppUser] FOREIGN KEY ([Created_User_ID]) REFERENCES [dbo].[p_AppUser] ([AppUser_ID]),
    CONSTRAINT [FK_p_TitleObject_Modified_User_ID_p_AppUser] FOREIGN KEY ([Modified_User_ID]) REFERENCES [dbo].[p_AppUser] ([AppUser_ID]),
    CONSTRAINT [FK_p_TitleObject_Parent_ID_p_TitleObject] FOREIGN KEY ([Parent_ID]) REFERENCES [dbo].[p_TitleObject] ([TitleObject_ID]),
    CONSTRAINT [FK_p_TitleObject_RowStatus_p_RowStatus] FOREIGN KEY ([RowStatus]) REFERENCES [dbo].[p_RowStatus] ([RowStatus_ID]),
    CONSTRAINT [UQ_p_TitleObject] UNIQUE NONCLUSTERED ([TitleObject_Code] ASC)
);



