CREATE TABLE [dbo].[p_TitleObject] (
    [TitleObject_ID]                     UNIQUEIDENTIFIER NOT NULL,
    [TitleObject_PARENTID]               UNIQUEIDENTIFIER NULL,
    [Structure]                          NVARCHAR (50)    NULL,
    [TitleObject_Name]                   NVARCHAR (100)   NOT NULL,
    [Description_Eng]                    NVARCHAR (300)   NULL,
    [Description_Rus]                    NVARCHAR (400)   NULL,
    [Phase_Name]                         NVARCHAR (100)   NULL,
    [ReportColor]                        NVARCHAR (50)    NULL,
    [ReportOrder]                        INT              NULL,
    [GLB_Weight]                         FLOAT (53)       CONSTRAINT [DF_TitleObject_ID] DEFAULT ((0)) NULL,
    [Row_Status]                         INT              NULL,
    [Insert_DTS]                         DATETIME2 (7)    NULL,
    [Update_DTS]                         DATETIME2 (7)    NULL,
    [Book1_Pct]                          FLOAT (53)       NULL,
    [Book1_Weight]                       FLOAT (53)       NULL,
    [Book2_Pct]                          FLOAT (53)       NULL,
    [Book2_Weight]                       FLOAT (53)       NULL,
    [Book3_Pct]                          FLOAT (53)       NULL,
    [Book3_Weight]                       FLOAT (53)       NULL,
    [Book4_Weight]                       FLOAT (53)       NULL,
    [TitleObject_for_ABDFinalSet]        NVARCHAR (100)   NULL,
    [Book1_Documents_Total]              FLOAT (53)       NULL,
    [Book1_Documents_received]           FLOAT (53)       NULL,
    [Book1_Progress]                     FLOAT (53)       NULL,
    [Book1_Documents_transmitted_to_CPY] FLOAT (53)       NULL,
    [StageOfConstr]                      NVARCHAR (10)    NULL,
    CONSTRAINT [PK_p_TitleObject] PRIMARY KEY CLUSTERED ([TitleObject_ID] ASC),
    CONSTRAINT [FK_p_TitleObject_Row_Status_p_RowStatus_sys] FOREIGN KEY ([Row_Status]) REFERENCES [dbo].[p_RowStatus_sys] ([Row_Status]),
    CONSTRAINT [UQ_p_TitleObject] UNIQUE NONCLUSTERED ([TitleObject_Name] ASC)
);

