CREATE TABLE [dbo].[p_WorkProgressQuantity] (
    [WorkProgressQuantity_ID] UNIQUEIDENTIFIER CONSTRAINT [DF_WorkProgressQuantity_ID] DEFAULT (newsequentialid()) NOT NULL,
    [Parent_ID]               UNIQUEIDENTIFIER NULL,
    [LogId]                   NVARCHAR (50)    NOT NULL,
    [WorkPackage_ID]          UNIQUEIDENTIFIER NOT NULL,
    [Num]                     NVARCHAR (50)    NULL,
    [TitleObject_ID]          UNIQUEIDENTIFIER NOT NULL,
    [Unit]                    NVARCHAR (500)   NULL,
    [Marka_ID]                UNIQUEIDENTIFIER NOT NULL,
    [Activity_Desc]           NVARCHAR (255)   NULL,
    [UOM]                     NVARCHAR (100)   NULL,
    [Design_Target]           NVARCHAR (255)   NULL,
    [Fact_Volume]             NVARCHAR (255)   NULL,
    [Fact_Percent]            FLOAT (53)       NULL,
    [Test_Done]               NVARCHAR (255)   NULL,
    [Acts_Prepared_CNT]       NVARCHAR (255)   NULL,
    [Acts_Prepared_Percent]   FLOAT (53)       NULL,
    [Reg]                     NVARCHAR (255)   NULL,
    [Under_Review_CNT]        NVARCHAR (255)   NULL,
    [Under_Review_Percent]    FLOAT (53)       NULL,
    [Commented_CNT]           NVARCHAR (255)   NULL,
    [Commented_Percent]       FLOAT (53)       NULL,
    [Approved_CNT]            NVARCHAR (255)   NULL,
    [Approved_Percent]        FLOAT (53)       NULL,
    [Multiple]                NVARCHAR (255)   NULL,
    [Issues]                  NVARCHAR (255)   NULL,
    [Row_Status]              INT              NOT NULL,
    [Insert_DTS]              DATETIME2 (7)    NOT NULL,
    [Update_DTS]              DATETIME2 (7)    NOT NULL,
    [Source_File]             NCHAR (255)      NULL,
    CONSTRAINT [PK_p_WorkProgressQuantity] PRIMARY KEY CLUSTERED ([WorkProgressQuantity_ID] ASC)
);

