CREATE TABLE [dbo].[p_WorkProgressCOWQuantity] (
    [WorkProgressCOWQuantity_ID] UNIQUEIDENTIFIER CONSTRAINT [DF_WorkProgressCOWQuantity_ID] DEFAULT (newsequentialid()) NOT NULL,
    [Parent_ID]                  UNIQUEIDENTIFIER NULL,
    [Log_ID]                     NVARCHAR (255)   NOT NULL,
    [WorkPackage_ID]             UNIQUEIDENTIFIER NOT NULL,
    [Cow]                        NVARCHAR (255)   NULL,
    [Swc_WorkClass_ID]           UNIQUEIDENTIFIER NOT NULL,
    [TitleObject_ID]             UNIQUEIDENTIFIER NOT NULL,
    [Module_ID]                  UNIQUEIDENTIFIER NOT NULL,
    [Marka_ID]                   UNIQUEIDENTIFIER NOT NULL,
    [Discpline_WorkClass_ID]     UNIQUEIDENTIFIER NOT NULL,
    [JobCard]                    NVARCHAR (100)   NULL,
    [Activity_Desc]              NVARCHAR (4000)  NULL,
    [JC_IsChecked]               INT              NULL,
    [1_req]                      INT              NULL,
    [1_reg]                      NVARCHAR (255)   NULL,
    [1_ABD_cur_state_ID]         UNIQUEIDENTIFIER NULL,
    [2_req]                      INT              NULL,
    [2_reg]                      NVARCHAR (255)   NULL,
    [2_ABD_cur_state_ID]         UNIQUEIDENTIFIER NULL,
    [3_req]                      INT              NULL,
    [3_reg]                      NVARCHAR (255)   NULL,
    [3_ABD_cur_state_ID]         UNIQUEIDENTIFIER NULL,
    [4_req]                      INT              NULL,
    [4_reg]                      NVARCHAR (255)   NULL,
    [4_ABD_cur_state_ID]         UNIQUEIDENTIFIER NULL,
    [5_req]                      INT              NULL,
    [5_reg]                      NVARCHAR (255)   NULL,
    [5_ABD_cur_state_ID]         UNIQUEIDENTIFIER NULL,
    [6_req]                      INT              NULL,
    [6_reg]                      NVARCHAR (255)   NULL,
    [6_ABD_cur_state_ID]         UNIQUEIDENTIFIER NULL,
    [7_req]                      INT              NULL,
    [7_reg]                      NVARCHAR (255)   NULL,
    [7_ABD_cur_state_ID]         UNIQUEIDENTIFIER NULL,
    [8_req]                      INT              NULL,
    [8_reg]                      NVARCHAR (255)   NULL,
    [8_ABD_cur_state_ID]         UNIQUEIDENTIFIER NULL,
    [9_req]                      INT              NULL,
    [9_reg]                      NVARCHAR (255)   NULL,
    [9_ABD_cur_state_ID]         UNIQUEIDENTIFIER NULL,
    [Issues]                     NVARCHAR (4000)  NULL,
    [Row_Status]                 INT              NOT NULL,
    [Insert_DTS]                 DATETIME2 (7)    NOT NULL,
    [Update_DTS]                 DATETIME2 (7)    NOT NULL,
    [Source_File]                NVARCHAR (500)   NULL,
    CONSTRAINT [PK_p_WorkProgressCOWQuantity] PRIMARY KEY CLUSTERED ([WorkProgressCOWQuantity_ID] ASC)
);

