CREATE TABLE [dbo].[ABD_Errors] (
    [Source_File]                           NVARCHAR (50)   NULL,
    [Load_Date]                             DATETIME2 (7)   NULL,
    [Title]                                 NVARCHAR (100)  NULL,
    [Marka]                                 NVARCHAR (100)  NULL,
    [Set_Number]                            NVARCHAR (100)  NULL,
    [Folder_Number]                         NVARCHAR (100)  NULL,
    [Structure]                             NVARCHAR (255)  NULL,
    [Unit]                                  NVARCHAR (100)  NULL,
    [Discipline]                            NVARCHAR (100)  NULL,
    [Doc_Type]                              NVARCHAR (255)  NULL,
    [SCTR]                                  NVARCHAR (255)  NULL,
    [Document_Sequiential_No_in_Folder]     NVARCHAR (255)  NULL,
    [GOST_Design_Drawing_No]                NVARCHAR (100)  NULL,
    [YLNG_Design_Drawing_No]                NVARCHAR (100)  NULL,
    [Document_No]                           NVARCHAR (100)  NULL,
    [Document_Title]                        NVARCHAR (4000) NULL,
    [Document_Issue_Date]                   NVARCHAR (100)  NULL,
    [Sheet_No_in_Folder]                    NVARCHAR (100)  NULL,
    [Total_sheets_No]                       NVARCHAR (100)  NULL,
    [Remarks]                               NVARCHAR (255)  NULL,
    [1251_Document_Issue_Date]              NVARCHAR (255)  NULL,
    [DATE_Complectation_Start_Date]         DATETIME        NULL,
    [INT_Document_Sequiential_No_in_Folder] INT             NULL,
    [INT_Sheet_No_in_Folder]                INT             NULL,
    [INT_Total_sheets_No]                   INT             NULL,
    [Converted Document_Title]              NVARCHAR (4000) NULL,
    [Row_Status]                            INT             NULL,
    [Trimmed Folder]                        NVARCHAR (100)  NULL,
    [Insert_DTS]                            DATETIME        NULL,
    [Update_DTS]                            DATETIME        NULL,
    [ErrorCode]                             INT             NULL,
    [ErrorColumn]                           INT             NULL
);

