CREATE TABLE [dbo].[s_ABD_ModErrors] (
    [Title]                             NVARCHAR (MAX) NULL,
    [Marka]                             NVARCHAR (MAX) NULL,
    [Set_Number]                        NVARCHAR (MAX) NULL,
    [Folder_Number]                     NVARCHAR (MAX) NULL,
    [Structure]                         NVARCHAR (MAX) NULL,
    [Unit]                              NVARCHAR (MAX) NULL,
    [Discipline]                        NVARCHAR (MAX) NULL,
    [Doc_Type]                          NVARCHAR (MAX) NULL,
    [SCTR]                              NVARCHAR (MAX) NULL,
    [Document_Sequiential_No_in_Folder] NVARCHAR (MAX) NULL,
    [GOST_Design_Drawing_No]            NVARCHAR (MAX) NULL,
    [YLNG_Design_Drawing_No]            NVARCHAR (MAX) NULL,
    [Document_No]                       NVARCHAR (MAX) NULL,
    [Document_Title]                    NVARCHAR (MAX) NULL,
    [Document_Issue_Date]               NVARCHAR (MAX) NULL,
    [Sheet_No_in_Folder]                NVARCHAR (MAX) NULL,
    [Total_sheets_No]                   NVARCHAR (MAX) NULL,
    [Remarks]                           NVARCHAR (MAX) NULL,
    [Source_File]                       NVARCHAR (MAX) NULL,
    [Load_Date]                         DATETIME2 (7)  NULL,
    [Error_Code]                        INT            NULL,
    [Error_Column]                      INT            NULL,
    [Reason]                            NVARCHAR (MAX) NULL,
    [Structure_Type]                    NVARCHAR (MAX) NULL,
    [Row_Status]                        INT            NULL
);

