CREATE TABLE [dbo].[s_ABD_Mod_Sorted] (
    [Folder_Number]                         NVARCHAR (255)   NULL,
    [Document_Sequiential_No_in_Folder]     NVARCHAR (255)   NULL,
    [Title]                                 NVARCHAR (MAX)   NULL,
    [Marka]                                 NVARCHAR (MAX)   NULL,
    [Set_Number]                            NVARCHAR (MAX)   NULL,
    [Structure]                             NVARCHAR (MAX)   NULL,
    [Unit]                                  NVARCHAR (MAX)   NULL,
    [Discipline]                            NVARCHAR (MAX)   NULL,
    [Doc_Type]                              NVARCHAR (MAX)   NULL,
    [SCTR]                                  NVARCHAR (MAX)   NULL,
    [GOST_Design_Drawing_No]                NVARCHAR (MAX)   NULL,
    [YLNG_Design_Drawing_No]                NVARCHAR (MAX)   NULL,
    [Document_No]                           NVARCHAR (MAX)   NULL,
    [Document_Title]                        NVARCHAR (MAX)   NULL,
    [Document_Issue_Date]                   NVARCHAR (MAX)   NULL,
    [Sheet_No_in_Folder]                    NVARCHAR (50)    NULL,
    [Total_sheets_No]                       NVARCHAR (50)    NULL,
    [Remarks]                               NVARCHAR (255)   NULL,
    [Source_File]                           NVARCHAR (MAX)   NULL,
    [Load_Date]                             DATETIME2 (7)    NULL,
    [INT_Document_Sequiential_No_in_Folder] INT              NULL,
    [INT_Sheet_No_in_Folder]                SMALLINT         NULL,
    [INT_Total_sheets_No]                   SMALLINT         NULL,
    [Converted Document_Title]              NVARCHAR (4000)  NULL,
    [Row_Status]                            INT              NULL,
    [Trimmed Folder]                        NVARCHAR (100)   NULL,
    [Insert_DTS]                            DATETIME         NULL,
    [Update_DTS]                            DATETIME         NULL,
    [ABDFinalFolder_ID]                     UNIQUEIDENTIFIER NULL,
    [ABDDocument_ID]                        UNIQUEIDENTIFIER NULL
);

