CREATE TABLE [dbo].[s_ABD_Mod] (
    [Title]                                 NVARCHAR (MAX)   NULL,
    [Marka]                                 NVARCHAR (MAX)   NULL,
    [Set_Number]                            NVARCHAR (MAX)   NULL,
    [Folder_Number]                         NVARCHAR (MAX)   NULL,
    [Structure]                             NVARCHAR (MAX)   NULL,
    [Unit]                                  NVARCHAR (MAX)   NULL,
    [Discipline]                            NVARCHAR (MAX)   NULL,
    [Doc_Type]                              NVARCHAR (MAX)   NULL,
    [SCTR]                                  NVARCHAR (MAX)   NULL,
    [Document_Sequiential_No_in_Folder]     NVARCHAR (MAX)   NULL,
    [GOST_Design_Drawing_No]                NVARCHAR (MAX)   NULL,
    [YLNG_Design_Drawing_No]                NVARCHAR (MAX)   NULL,
    [Document_No]                           NVARCHAR (MAX)   NULL,
    [Document_Title]                        NVARCHAR (MAX)   NULL,
    [Document_Issue_Date]                   NVARCHAR (MAX)   NULL,
    [Sheet_No_in_Folder]                    NVARCHAR (MAX)   NULL,
    [Total_sheets_No]                       NVARCHAR (MAX)   NULL,
    [Remarks]                               NVARCHAR (MAX)   NULL,
    [Source_File]                           NVARCHAR (MAX)   NULL,
    [Load_Date]                             DATETIME2 (7)    NULL,
    [Structure_Type]                        NVARCHAR (MAX)   NULL,
    [ABDFinalFolder_ID]                     UNIQUEIDENTIFIER NULL,
    [INT_Document_Sequiential_No_in_Folder] INT              NULL,
    [INT_Sheet_No_in_Folder]                INT              NULL,
    [INT_Total_sheets_No]                   INT              NULL,
    [DATE_Document_Issue_Date]              DATETIME2 (7)    NULL,
    [GOST_ID]                               UNIQUEIDENTIFIER NULL,
    [Structure_ID]                          UNIQUEIDENTIFIER NULL,
    [PID_ID]                                UNIQUEIDENTIFIER NULL,
    [Contragent_ID]                         UNIQUEIDENTIFIER NULL,
    [ABDDocument_ID]                        UNIQUEIDENTIFIER NULL
);

