CREATE TABLE [dbo].[s_Final_ABD_Compilation_LOGErrors] (
    [Stage]                    NVARCHAR (MAX) NULL,
    [Title]                    NVARCHAR (MAX) NULL,
    [C_Name]                   NVARCHAR (MAX) NULL,
    [Marka]                    NVARCHAR (MAX) NULL,
    [Marka_Description]        NVARCHAR (MAX) NULL,
    [Set]                      NVARCHAR (MAX) NULL,
    [Folder]                   NVARCHAR (MAX) NULL,
    [Status]                   NVARCHAR (MAX) NULL,
    [TN_Number]                NVARCHAR (MAX) NULL,
    [TN_Date]                  NVARCHAR (MAX) NULL,
    [Draw_Number]              NVARCHAR (MAX) NULL,
    [Draw_GOST]                NVARCHAR (MAX) NULL,
    [C_Object]                 NVARCHAR (MAX) NULL,
    [Complectation_Start_Date] NVARCHAR (MAX) NULL,
    [C_YAM]                    NVARCHAR (MAX) NULL,
    [C_VEL]                    NVARCHAR (MAX) NULL,
    [C_ZPGS]                   NVARCHAR (MAX) NULL,
    [C_KXM]                    NVARCHAR (MAX) NULL,
    [C_REGA]                   NVARCHAR (MAX) NULL,
    [C_NOVA]                   NVARCHAR (MAX) NULL,
    [C_SNEMA]                  NVARCHAR (MAX) NULL,
    [COW_Marka]                NVARCHAR (MAX) NULL,
    [STL_Rep]                  NVARCHAR (MAX) NULL,
    [Initial_Reg]              NVARCHAR (MAX) NULL,
    [Folder_List_Number]       NVARCHAR (MAX) NULL,
    [Remark]                   NVARCHAR (MAX) NULL,
    [C_PSIS]                   NVARCHAR (MAX) NULL,
    [Source_File]              NVARCHAR (MAX) NULL,
    [Load_Date]                DATETIME2 (7)  NULL,
    [Error_Code]               INT            NULL,
    [Error_Column]             INT            NULL,
    [Reason]                   NVARCHAR (MAX) NULL
);

