CREATE TABLE [dbo].[s_TestpackDetailsReportErrors] (
    [F1]           INT            NULL,
    [F2]           NVARCHAR (MAX) NULL,
    [F3]           NVARCHAR (MAX) NULL,
    [F4]           NVARCHAR (MAX) NULL,
    [F5]           NVARCHAR (MAX) NULL,
    [F6]           NVARCHAR (MAX) NULL,
    [F7]           NVARCHAR (MAX) NULL,
    [F8]           NVARCHAR (MAX) NULL,
    [F9]           NVARCHAR (MAX) NULL,
    [F10]          NVARCHAR (MAX) NULL,
    [F11]          NVARCHAR (MAX) NULL,
    [F12]          NVARCHAR (MAX) NULL,
    [F13]          NVARCHAR (MAX) NULL,
    [F14]          NVARCHAR (MAX) NULL,
    [F15]          NVARCHAR (MAX) NULL,
    [F16]          NVARCHAR (MAX) NULL,
    [F17]          NVARCHAR (MAX) NULL,
    [F18]          NVARCHAR (MAX) NULL,
    [F19]          NVARCHAR (MAX) NULL,
    [F20]          NVARCHAR (MAX) NULL,
    [F21]          NVARCHAR (MAX) NULL,
    [F22]          NVARCHAR (MAX) NULL,
    [F23]          NVARCHAR (MAX) NULL,
    [F24]          NVARCHAR (MAX) NULL,
    [F25]          NVARCHAR (MAX) NULL,
    [F26]          NVARCHAR (MAX) NULL,
    [F27]          NVARCHAR (MAX) NULL,
    [F28]          NVARCHAR (MAX) NULL,
    [F29]          NVARCHAR (MAX) NULL,
    [F30]          NVARCHAR (MAX) NULL,
    [F31]          NVARCHAR (MAX) NULL,
    [F32]          NVARCHAR (MAX) NULL,
    [F33]          NVARCHAR (MAX) NULL,
    [F34]          NVARCHAR (MAX) NULL,
    [F35]          NVARCHAR (MAX) NULL,
    [F36]          NVARCHAR (MAX) NULL,
    [F37]          NVARCHAR (MAX) NULL,
    [F38]          NVARCHAR (MAX) NULL,
    [Source_File]  NVARCHAR (MAX) NULL,
    [Load_Date]    DATETIME2 (7)  NULL,
    [Error_Code]   INT            NULL,
    [Error_Column] INT            NULL,
    [Reason]       NVARCHAR (MAX) NULL
);

