CREATE TABLE [dbo].[tr_zzz] (
    [Log_ID]                   NVARCHAR (MAX) NULL,
    [Phase]                    NVARCHAR (MAX) NULL,
    [Title]                    NVARCHAR (MAX) NULL,
    [Marka]                    NVARCHAR (MAX) NULL,
    [Line]                     NVARCHAR (MAX) NULL,
    [Design_Area]              NVARCHAR (MAX) NULL,
    [Sheet]                    NVARCHAR (MAX) NULL,
    [ISO]                      NVARCHAR (MAX) NULL,
    [Shop_Weld_RegNum]         NVARCHAR (MAX) NULL,
    [Shop_Weld_AD_cur_State]   NVARCHAR (MAX) NULL,
    [Shop_Weld_Issued_SCTR]    NVARCHAR (MAX) NULL,
    [Shop_Weld_Accepted_CPY]   NVARCHAR (MAX) NULL,
    [Field_Weld_RegNum]        NVARCHAR (MAX) NULL,
    [Field_Weld_cur_State]     NVARCHAR (MAX) NULL,
    [Field_Weld_Issued_SCTR]   NVARCHAR (MAX) NULL,
    [Field_Weld_Accepted_CPY]  NVARCHAR (MAX) NULL,
    [AKZ_Shop_RegNum]          NVARCHAR (MAX) NULL,
    [AKZ_Shop_cur_State]       NVARCHAR (MAX) NULL,
    [AKZ_Shop_Issued_SCTR]     NVARCHAR (MAX) NULL,
    [AKZ_Shop_Accepted_CPY]    NVARCHAR (MAX) NULL,
    [AKZ_Weld_RegNum]          NVARCHAR (MAX) NULL,
    [AKZ_Weld_cur_State]       NVARCHAR (MAX) NULL,
    [AKZ_Weld_Issued_SCTR]     NVARCHAR (MAX) NULL,
    [AKZ_Weld_Accepted_CPY]    NVARCHAR (MAX) NULL,
    [GW_RegNum_RegNum]         NVARCHAR (MAX) NULL,
    [GW_cur_State]             NVARCHAR (MAX) NULL,
    [GW_Issued_SCTR]           NVARCHAR (MAX) NULL,
    [GW_Accepted_CPY]          NVARCHAR (MAX) NULL,
    [Insulation_RegNum]        NVARCHAR (MAX) NULL,
    [Insulation_cur_State]     NVARCHAR (MAX) NULL,
    [Insulation_Issued_SCTR]   NVARCHAR (MAX) NULL,
    [Insulation_Accepted_CPY]  NVARCHAR (MAX) NULL,
    [Test_Density_Strength]    NVARCHAR (MAX) NULL,
    [Test_Leak]                NVARCHAR (MAX) NULL,
    [Certificate_Installation] NVARCHAR (MAX) NULL,
    [Source_File]              NVARCHAR (MAX) NULL,
    [Load_Date]                DATETIME2 (7)  NULL,
    [Error_Code]               INT            NULL,
    [Error_Column]             INT            NULL,
    [Reason]                   NVARCHAR (MAX) NULL
);

