CREATE TABLE [dbo].[p_FileShareTable_Draft] AS FILETABLE FILESTREAM_ON [FilestreamFG]
WITH (FILETABLE_COLLATE_FILENAME = SQL_Latin1_General_CP1_CI_AS, FILETABLE_DIRECTORY = N'25_AsBuilt_Documentation_Draft');

