CREATE TABLE [dbo].[p_FileShareTable] AS FILETABLE FILESTREAM_ON [FilestreamFG]
WITH (FILETABLE_COLLATE_FILENAME = SQL_Latin1_General_CP1_CI_AS, FILETABLE_DIRECTORY = N'25_AsBuilt_Documentation', FILETABLE_PRIMARY_KEY_CONSTRAINT_NAME = [PK_FileShare]);

