//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.WebDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Register_to_Document
    {
        public System.Guid Register_to_Document_ID { get; set; }
        public int RowStatus { get; set; }
        public System.DateTime Insert_DTS { get; set; }
        public System.DateTime Update_DTS { get; set; }
        public System.Guid Created_User_ID { get; set; }
        public System.Guid Modified_User_ID { get; set; }
        public System.Guid Register_ID { get; set; }
        public System.Guid Document_ID { get; set; }
        public int Iteration { get; set; }
        public Nullable<int> NumberInRegister { get; set; }
        public Nullable<int> SheetFolderNumber { get; set; }
        public string Comment { get; set; }
    }
}
