//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.WebDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register_to_TitleObject
    {
        public System.Guid Register_to_TitleObject_ID { get; set; }
        public System.Guid Register_ID { get; set; }
        public System.Guid TitleObject_ID { get; set; }
        public int Iteration { get; set; }
    }
}
