//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.WebDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WEB_MainDataEntities : DbContext
    {
        public WEB_MainDataEntities()
            : base("name=WEB_MainDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UI_Register_ListItem> UI_Register_ListItem { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<UI_Document_to_GOST> UI_Document_to_GOST { get; set; }
        public virtual DbSet<UI_Document_to_PID> UI_Document_to_PID { get; set; }
        public virtual DbSet<GOST> GOSTs { get; set; }
        public virtual DbSet<PID> PIDs { get; set; }
        public virtual DbSet<UI_Document_List> UI_Document_List { get; set; }
        public virtual DbSet<T_Document> T_Document { get; set; }
        public virtual DbSet<T_Document_List> T_Document_List { get; set; }
        public virtual DbSet<DocumentProjectNumber> DocumentProjectNumbers { get; set; }
        public virtual DbSet<TitleObject> TitleObjects { get; set; }
        public virtual DbSet<UI_StatusRelation> UI_StatusRelation { get; set; }
        public virtual DbSet<Marka> Markas { get; set; }
        public virtual DbSet<WorkPackage> WorkPackages { get; set; }
        public virtual DbSet<UI_Document_to_Marka> UI_Document_to_Marka { get; set; }
        public virtual DbSet<UI_Document_to_TitleObject> UI_Document_to_TitleObject { get; set; }
        public virtual DbSet<p_Register_to_Marka> p_Register_to_Marka { get; set; }
        public virtual DbSet<p_Register_to_TitleObject> p_Register_to_TitleObject { get; set; }
        public virtual DbSet<Register_to_Marka> Register_to_Marka { get; set; }
        public virtual DbSet<Register_to_TitleObject> Register_to_TitleObject { get; set; }
        public virtual DbSet<p_Register_to_Document> p_Register_to_Document { get; set; }
        public virtual DbSet<T_CheckList> T_CheckList { get; set; }
        public virtual DbSet<T_Register_List> T_Register_List { get; set; }
        public virtual DbSet<T_CheckItem> T_CheckItem { get; set; }
        public virtual DbSet<UI_Register_List> UI_Register_List { get; set; }
        public virtual DbSet<UI_FileStream> UI_FileStream { get; set; }
        public virtual DbSet<UI_CheckItem> UI_CheckItem { get; set; }
        public virtual DbSet<UI_CheckList> UI_CheckList { get; set; }
    
        public virtual ObjectResult<Nullable<long>> Register_SequenceNumber()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("Register_SequenceNumber");
        }
    
        public virtual ObjectResult<Document_Delete_Result> Document_Delete(string i_AppUser_ID, string i_Document_ID, ObjectParameter o_IsError)
        {
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Document_IDParameter = i_Document_ID != null ?
                new ObjectParameter("i_Document_ID", i_Document_ID) :
                new ObjectParameter("i_Document_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Document_Delete_Result>("Document_Delete", i_AppUser_IDParameter, i_Document_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<Document_Insert_Result> Document_Insert(string i_RowStatus, string i_AppUser_ID, string i_Document_Code, string i_Document_Number, string i_DocumentType_ID, string i_Document_Date, string i_Issue_Date, string i_TotalSheets, string i_Document_Name, string i_Parent_ID, ObjectParameter o_Entity_ID, ObjectParameter o_IsError)
        {
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Document_CodeParameter = i_Document_Code != null ?
                new ObjectParameter("i_Document_Code", i_Document_Code) :
                new ObjectParameter("i_Document_Code", typeof(string));
    
            var i_Document_NumberParameter = i_Document_Number != null ?
                new ObjectParameter("i_Document_Number", i_Document_Number) :
                new ObjectParameter("i_Document_Number", typeof(string));
    
            var i_DocumentType_IDParameter = i_DocumentType_ID != null ?
                new ObjectParameter("i_DocumentType_ID", i_DocumentType_ID) :
                new ObjectParameter("i_DocumentType_ID", typeof(string));
    
            var i_Document_DateParameter = i_Document_Date != null ?
                new ObjectParameter("i_Document_Date", i_Document_Date) :
                new ObjectParameter("i_Document_Date", typeof(string));
    
            var i_Issue_DateParameter = i_Issue_Date != null ?
                new ObjectParameter("i_Issue_Date", i_Issue_Date) :
                new ObjectParameter("i_Issue_Date", typeof(string));
    
            var i_TotalSheetsParameter = i_TotalSheets != null ?
                new ObjectParameter("i_TotalSheets", i_TotalSheets) :
                new ObjectParameter("i_TotalSheets", typeof(string));
    
            var i_Document_NameParameter = i_Document_Name != null ?
                new ObjectParameter("i_Document_Name", i_Document_Name) :
                new ObjectParameter("i_Document_Name", typeof(string));
    
            var i_Parent_IDParameter = i_Parent_ID != null ?
                new ObjectParameter("i_Parent_ID", i_Parent_ID) :
                new ObjectParameter("i_Parent_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Document_Insert_Result>("Document_Insert", i_RowStatusParameter, i_AppUser_IDParameter, i_Document_CodeParameter, i_Document_NumberParameter, i_DocumentType_IDParameter, i_Document_DateParameter, i_Issue_DateParameter, i_TotalSheetsParameter, i_Document_NameParameter, i_Parent_IDParameter, o_Entity_ID, o_IsError);
        }
    
        public virtual ObjectResult<Document_To_FileTable_Delete_Result> Document_To_FileTable_Delete(string i_AppUser_ID, string i_Document_to_FileTable_ID, ObjectParameter o_IsError)
        {
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Document_to_FileTable_IDParameter = i_Document_to_FileTable_ID != null ?
                new ObjectParameter("i_Document_to_FileTable_ID", i_Document_to_FileTable_ID) :
                new ObjectParameter("i_Document_to_FileTable_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Document_To_FileTable_Delete_Result>("Document_To_FileTable_Delete", i_AppUser_IDParameter, i_Document_to_FileTable_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<Document_to_FileTable_Insert_Result> Document_to_FileTable_Insert(string i_RowStatus, string i_AppUser_ID, string i_Document_ID, string i_FileTable_ID, ObjectParameter o_Entity_ID, ObjectParameter o_IsError)
        {
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Document_IDParameter = i_Document_ID != null ?
                new ObjectParameter("i_Document_ID", i_Document_ID) :
                new ObjectParameter("i_Document_ID", typeof(string));
    
            var i_FileTable_IDParameter = i_FileTable_ID != null ?
                new ObjectParameter("i_FileTable_ID", i_FileTable_ID) :
                new ObjectParameter("i_FileTable_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Document_to_FileTable_Insert_Result>("Document_to_FileTable_Insert", i_RowStatusParameter, i_AppUser_IDParameter, i_Document_IDParameter, i_FileTable_IDParameter, o_Entity_ID, o_IsError);
        }
    
        public virtual ObjectResult<Document_to_FileTable_Update_Result> Document_to_FileTable_Update(string i_Document_to_FileTable_ID, string i_RowStatus, string i_AppUser_ID, string i_Document_ID, string i_FileTable_ID, ObjectParameter o_IsError)
        {
            var i_Document_to_FileTable_IDParameter = i_Document_to_FileTable_ID != null ?
                new ObjectParameter("i_Document_to_FileTable_ID", i_Document_to_FileTable_ID) :
                new ObjectParameter("i_Document_to_FileTable_ID", typeof(string));
    
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Document_IDParameter = i_Document_ID != null ?
                new ObjectParameter("i_Document_ID", i_Document_ID) :
                new ObjectParameter("i_Document_ID", typeof(string));
    
            var i_FileTable_IDParameter = i_FileTable_ID != null ?
                new ObjectParameter("i_FileTable_ID", i_FileTable_ID) :
                new ObjectParameter("i_FileTable_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Document_to_FileTable_Update_Result>("Document_to_FileTable_Update", i_Document_to_FileTable_IDParameter, i_RowStatusParameter, i_AppUser_IDParameter, i_Document_IDParameter, i_FileTable_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<Document_Update_Result> Document_Update(string i_Document_ID, string i_RowStatus, string i_AppUser_ID, string i_Document_Code, string i_Document_Number, string i_DocumentType_ID, string i_Document_Date, string i_Issue_Date, string i_TotalSheets, string i_Document_Name, string i_Parent_ID, ObjectParameter o_IsError)
        {
            var i_Document_IDParameter = i_Document_ID != null ?
                new ObjectParameter("i_Document_ID", i_Document_ID) :
                new ObjectParameter("i_Document_ID", typeof(string));
    
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Document_CodeParameter = i_Document_Code != null ?
                new ObjectParameter("i_Document_Code", i_Document_Code) :
                new ObjectParameter("i_Document_Code", typeof(string));
    
            var i_Document_NumberParameter = i_Document_Number != null ?
                new ObjectParameter("i_Document_Number", i_Document_Number) :
                new ObjectParameter("i_Document_Number", typeof(string));
    
            var i_DocumentType_IDParameter = i_DocumentType_ID != null ?
                new ObjectParameter("i_DocumentType_ID", i_DocumentType_ID) :
                new ObjectParameter("i_DocumentType_ID", typeof(string));
    
            var i_Document_DateParameter = i_Document_Date != null ?
                new ObjectParameter("i_Document_Date", i_Document_Date) :
                new ObjectParameter("i_Document_Date", typeof(string));
    
            var i_Issue_DateParameter = i_Issue_Date != null ?
                new ObjectParameter("i_Issue_Date", i_Issue_Date) :
                new ObjectParameter("i_Issue_Date", typeof(string));
    
            var i_TotalSheetsParameter = i_TotalSheets != null ?
                new ObjectParameter("i_TotalSheets", i_TotalSheets) :
                new ObjectParameter("i_TotalSheets", typeof(string));
    
            var i_Document_NameParameter = i_Document_Name != null ?
                new ObjectParameter("i_Document_Name", i_Document_Name) :
                new ObjectParameter("i_Document_Name", typeof(string));
    
            var i_Parent_IDParameter = i_Parent_ID != null ?
                new ObjectParameter("i_Parent_ID", i_Parent_ID) :
                new ObjectParameter("i_Parent_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Document_Update_Result>("Document_Update", i_Document_IDParameter, i_RowStatusParameter, i_AppUser_IDParameter, i_Document_CodeParameter, i_Document_NumberParameter, i_DocumentType_IDParameter, i_Document_DateParameter, i_Issue_DateParameter, i_TotalSheetsParameter, i_Document_NameParameter, i_Parent_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<DocumentType_Delete_Result> DocumentType_Delete(string i_AppUser_ID, string i_DocumentType_ID, ObjectParameter o_IsError)
        {
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_DocumentType_IDParameter = i_DocumentType_ID != null ?
                new ObjectParameter("i_DocumentType_ID", i_DocumentType_ID) :
                new ObjectParameter("i_DocumentType_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocumentType_Delete_Result>("DocumentType_Delete", i_AppUser_IDParameter, i_DocumentType_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<DocumentType_Insert_Result> DocumentType_Insert(string i_RowStatus, string i_AppUser_ID, string i_DocumentType_Code, ObjectParameter o_Entity_ID, ObjectParameter o_IsError)
        {
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_DocumentType_CodeParameter = i_DocumentType_Code != null ?
                new ObjectParameter("i_DocumentType_Code", i_DocumentType_Code) :
                new ObjectParameter("i_DocumentType_Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocumentType_Insert_Result>("DocumentType_Insert", i_RowStatusParameter, i_AppUser_IDParameter, i_DocumentType_CodeParameter, o_Entity_ID, o_IsError);
        }
    
        public virtual ObjectResult<DocumentType_Update_Result> DocumentType_Update(string i_DocumentType_ID, string i_RowStatus, string i_AppUser_ID, string i_DocumentType_Code, ObjectParameter o_IsError)
        {
            var i_DocumentType_IDParameter = i_DocumentType_ID != null ?
                new ObjectParameter("i_DocumentType_ID", i_DocumentType_ID) :
                new ObjectParameter("i_DocumentType_ID", typeof(string));
    
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_DocumentType_CodeParameter = i_DocumentType_Code != null ?
                new ObjectParameter("i_DocumentType_Code", i_DocumentType_Code) :
                new ObjectParameter("i_DocumentType_Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocumentType_Update_Result>("DocumentType_Update", i_DocumentType_IDParameter, i_RowStatusParameter, i_AppUser_IDParameter, i_DocumentType_CodeParameter, o_IsError);
        }
    
        public virtual ObjectResult<Register_Delete_Result> Register_Delete(string i_AppUser_ID, string i_Register_ID, ObjectParameter o_IsError)
        {
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Register_IDParameter = i_Register_ID != null ?
                new ObjectParameter("i_Register_ID", i_Register_ID) :
                new ObjectParameter("i_Register_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Register_Delete_Result>("Register_Delete", i_AppUser_IDParameter, i_Register_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<Register_Insert_Result> Register_Insert(string i_RowStatus, string i_AppUser_ID, string i_Register_Code, string i_Register_Date, string i_Current_Iteration, string i_Customer_ID, string i_Contractor_ID, string i_SubContractor_ID, string i_Resp_Employee_ID, string i_WorkPackage_ID, string i_Comment, ObjectParameter o_Entity_ID, ObjectParameter o_IsError)
        {
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Register_CodeParameter = i_Register_Code != null ?
                new ObjectParameter("i_Register_Code", i_Register_Code) :
                new ObjectParameter("i_Register_Code", typeof(string));
    
            var i_Register_DateParameter = i_Register_Date != null ?
                new ObjectParameter("i_Register_Date", i_Register_Date) :
                new ObjectParameter("i_Register_Date", typeof(string));
    
            var i_Current_IterationParameter = i_Current_Iteration != null ?
                new ObjectParameter("i_Current_Iteration", i_Current_Iteration) :
                new ObjectParameter("i_Current_Iteration", typeof(string));
    
            var i_Customer_IDParameter = i_Customer_ID != null ?
                new ObjectParameter("i_Customer_ID", i_Customer_ID) :
                new ObjectParameter("i_Customer_ID", typeof(string));
    
            var i_Contractor_IDParameter = i_Contractor_ID != null ?
                new ObjectParameter("i_Contractor_ID", i_Contractor_ID) :
                new ObjectParameter("i_Contractor_ID", typeof(string));
    
            var i_SubContractor_IDParameter = i_SubContractor_ID != null ?
                new ObjectParameter("i_SubContractor_ID", i_SubContractor_ID) :
                new ObjectParameter("i_SubContractor_ID", typeof(string));
    
            var i_Resp_Employee_IDParameter = i_Resp_Employee_ID != null ?
                new ObjectParameter("i_Resp_Employee_ID", i_Resp_Employee_ID) :
                new ObjectParameter("i_Resp_Employee_ID", typeof(string));
    
            var i_WorkPackage_IDParameter = i_WorkPackage_ID != null ?
                new ObjectParameter("i_WorkPackage_ID", i_WorkPackage_ID) :
                new ObjectParameter("i_WorkPackage_ID", typeof(string));
    
            var i_CommentParameter = i_Comment != null ?
                new ObjectParameter("i_Comment", i_Comment) :
                new ObjectParameter("i_Comment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Register_Insert_Result>("Register_Insert", i_RowStatusParameter, i_AppUser_IDParameter, i_Register_CodeParameter, i_Register_DateParameter, i_Current_IterationParameter, i_Customer_IDParameter, i_Contractor_IDParameter, i_SubContractor_IDParameter, i_Resp_Employee_IDParameter, i_WorkPackage_IDParameter, i_CommentParameter, o_Entity_ID, o_IsError);
        }
    
        public virtual ObjectResult<Register_To_Document_Delete_Result> Register_To_Document_Delete(string i_AppUser_ID, string i_Register_to_Document_ID, ObjectParameter o_IsError)
        {
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Register_to_Document_IDParameter = i_Register_to_Document_ID != null ?
                new ObjectParameter("i_Register_to_Document_ID", i_Register_to_Document_ID) :
                new ObjectParameter("i_Register_to_Document_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Register_To_Document_Delete_Result>("Register_To_Document_Delete", i_AppUser_IDParameter, i_Register_to_Document_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<Register_to_Document_Insert_Result> Register_to_Document_Insert(string i_RowStatus, string i_AppUser_ID, string i_Register_ID, string i_Document_ID, string i_Iteration, string i_NumberInRegister, string i_SheetFolderNumber, string i_Comment, ObjectParameter o_Entity_ID, ObjectParameter o_IsError)
        {
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Register_IDParameter = i_Register_ID != null ?
                new ObjectParameter("i_Register_ID", i_Register_ID) :
                new ObjectParameter("i_Register_ID", typeof(string));
    
            var i_Document_IDParameter = i_Document_ID != null ?
                new ObjectParameter("i_Document_ID", i_Document_ID) :
                new ObjectParameter("i_Document_ID", typeof(string));
    
            var i_IterationParameter = i_Iteration != null ?
                new ObjectParameter("i_Iteration", i_Iteration) :
                new ObjectParameter("i_Iteration", typeof(string));
    
            var i_NumberInRegisterParameter = i_NumberInRegister != null ?
                new ObjectParameter("i_NumberInRegister", i_NumberInRegister) :
                new ObjectParameter("i_NumberInRegister", typeof(string));
    
            var i_SheetFolderNumberParameter = i_SheetFolderNumber != null ?
                new ObjectParameter("i_SheetFolderNumber", i_SheetFolderNumber) :
                new ObjectParameter("i_SheetFolderNumber", typeof(string));
    
            var i_CommentParameter = i_Comment != null ?
                new ObjectParameter("i_Comment", i_Comment) :
                new ObjectParameter("i_Comment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Register_to_Document_Insert_Result>("Register_to_Document_Insert", i_RowStatusParameter, i_AppUser_IDParameter, i_Register_IDParameter, i_Document_IDParameter, i_IterationParameter, i_NumberInRegisterParameter, i_SheetFolderNumberParameter, i_CommentParameter, o_Entity_ID, o_IsError);
        }
    
        public virtual ObjectResult<Register_to_Document_Update_Result> Register_to_Document_Update(string i_Register_to_Document_ID, string i_RowStatus, string i_AppUser_ID, string i_Register_ID, string i_Document_ID, string i_Iteration, string i_NumberInRegister, string i_SheetFolderNumber, string i_Comment, ObjectParameter o_IsError)
        {
            var i_Register_to_Document_IDParameter = i_Register_to_Document_ID != null ?
                new ObjectParameter("i_Register_to_Document_ID", i_Register_to_Document_ID) :
                new ObjectParameter("i_Register_to_Document_ID", typeof(string));
    
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Register_IDParameter = i_Register_ID != null ?
                new ObjectParameter("i_Register_ID", i_Register_ID) :
                new ObjectParameter("i_Register_ID", typeof(string));
    
            var i_Document_IDParameter = i_Document_ID != null ?
                new ObjectParameter("i_Document_ID", i_Document_ID) :
                new ObjectParameter("i_Document_ID", typeof(string));
    
            var i_IterationParameter = i_Iteration != null ?
                new ObjectParameter("i_Iteration", i_Iteration) :
                new ObjectParameter("i_Iteration", typeof(string));
    
            var i_NumberInRegisterParameter = i_NumberInRegister != null ?
                new ObjectParameter("i_NumberInRegister", i_NumberInRegister) :
                new ObjectParameter("i_NumberInRegister", typeof(string));
    
            var i_SheetFolderNumberParameter = i_SheetFolderNumber != null ?
                new ObjectParameter("i_SheetFolderNumber", i_SheetFolderNumber) :
                new ObjectParameter("i_SheetFolderNumber", typeof(string));
    
            var i_CommentParameter = i_Comment != null ?
                new ObjectParameter("i_Comment", i_Comment) :
                new ObjectParameter("i_Comment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Register_to_Document_Update_Result>("Register_to_Document_Update", i_Register_to_Document_IDParameter, i_RowStatusParameter, i_AppUser_IDParameter, i_Register_IDParameter, i_Document_IDParameter, i_IterationParameter, i_NumberInRegisterParameter, i_SheetFolderNumberParameter, i_CommentParameter, o_IsError);
        }
    
        public virtual ObjectResult<Register_To_Status_Delete_Result> Register_To_Status_Delete(string i_AppUser_ID, string i_Register_to_Status_ID, ObjectParameter o_IsError)
        {
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Register_to_Status_IDParameter = i_Register_to_Status_ID != null ?
                new ObjectParameter("i_Register_to_Status_ID", i_Register_to_Status_ID) :
                new ObjectParameter("i_Register_to_Status_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Register_To_Status_Delete_Result>("Register_To_Status_Delete", i_AppUser_IDParameter, i_Register_to_Status_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<Register_to_Status_Insert_Result> Register_to_Status_Insert(string i_RowStatus, string i_AppUser_ID, string i_Register_ID, string i_Status_ID, string i_Iteration, string i_DTS_Start, string i_DTS_End, string i_Parent_ID, ObjectParameter o_Entity_ID, ObjectParameter o_IsError)
        {
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Register_IDParameter = i_Register_ID != null ?
                new ObjectParameter("i_Register_ID", i_Register_ID) :
                new ObjectParameter("i_Register_ID", typeof(string));
    
            var i_Status_IDParameter = i_Status_ID != null ?
                new ObjectParameter("i_Status_ID", i_Status_ID) :
                new ObjectParameter("i_Status_ID", typeof(string));
    
            var i_IterationParameter = i_Iteration != null ?
                new ObjectParameter("i_Iteration", i_Iteration) :
                new ObjectParameter("i_Iteration", typeof(string));
    
            var i_DTS_StartParameter = i_DTS_Start != null ?
                new ObjectParameter("i_DTS_Start", i_DTS_Start) :
                new ObjectParameter("i_DTS_Start", typeof(string));
    
            var i_DTS_EndParameter = i_DTS_End != null ?
                new ObjectParameter("i_DTS_End", i_DTS_End) :
                new ObjectParameter("i_DTS_End", typeof(string));
    
            var i_Parent_IDParameter = i_Parent_ID != null ?
                new ObjectParameter("i_Parent_ID", i_Parent_ID) :
                new ObjectParameter("i_Parent_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Register_to_Status_Insert_Result>("Register_to_Status_Insert", i_RowStatusParameter, i_AppUser_IDParameter, i_Register_IDParameter, i_Status_IDParameter, i_IterationParameter, i_DTS_StartParameter, i_DTS_EndParameter, i_Parent_IDParameter, o_Entity_ID, o_IsError);
        }
    
        public virtual ObjectResult<Register_to_Status_Update_Result> Register_to_Status_Update(string i_Register_to_Status_ID, string i_RowStatus, string i_AppUser_ID, string i_Register_ID, string i_Status_ID, string i_Parent_ID, string i_Iteration, string i_DTS_Start, string i_DTS_End, ObjectParameter o_IsError)
        {
            var i_Register_to_Status_IDParameter = i_Register_to_Status_ID != null ?
                new ObjectParameter("i_Register_to_Status_ID", i_Register_to_Status_ID) :
                new ObjectParameter("i_Register_to_Status_ID", typeof(string));
    
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Register_IDParameter = i_Register_ID != null ?
                new ObjectParameter("i_Register_ID", i_Register_ID) :
                new ObjectParameter("i_Register_ID", typeof(string));
    
            var i_Status_IDParameter = i_Status_ID != null ?
                new ObjectParameter("i_Status_ID", i_Status_ID) :
                new ObjectParameter("i_Status_ID", typeof(string));
    
            var i_Parent_IDParameter = i_Parent_ID != null ?
                new ObjectParameter("i_Parent_ID", i_Parent_ID) :
                new ObjectParameter("i_Parent_ID", typeof(string));
    
            var i_IterationParameter = i_Iteration != null ?
                new ObjectParameter("i_Iteration", i_Iteration) :
                new ObjectParameter("i_Iteration", typeof(string));
    
            var i_DTS_StartParameter = i_DTS_Start != null ?
                new ObjectParameter("i_DTS_Start", i_DTS_Start) :
                new ObjectParameter("i_DTS_Start", typeof(string));
    
            var i_DTS_EndParameter = i_DTS_End != null ?
                new ObjectParameter("i_DTS_End", i_DTS_End) :
                new ObjectParameter("i_DTS_End", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Register_to_Status_Update_Result>("Register_to_Status_Update", i_Register_to_Status_IDParameter, i_RowStatusParameter, i_AppUser_IDParameter, i_Register_IDParameter, i_Status_IDParameter, i_Parent_IDParameter, i_IterationParameter, i_DTS_StartParameter, i_DTS_EndParameter, o_IsError);
        }
    
        public virtual ObjectResult<Register_Update_Result> Register_Update(string i_Register_ID, string i_RowStatus, string i_AppUser_ID, string i_Register_Code, string i_Register_Date, string i_Current_Iteration, string i_Customer_ID, string i_Contractor_ID, string i_SubContractor_ID, string i_Resp_Employee_ID, string i_WorkPackage_ID, string i_Comment, ObjectParameter o_IsError)
        {
            var i_Register_IDParameter = i_Register_ID != null ?
                new ObjectParameter("i_Register_ID", i_Register_ID) :
                new ObjectParameter("i_Register_ID", typeof(string));
    
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Register_CodeParameter = i_Register_Code != null ?
                new ObjectParameter("i_Register_Code", i_Register_Code) :
                new ObjectParameter("i_Register_Code", typeof(string));
    
            var i_Register_DateParameter = i_Register_Date != null ?
                new ObjectParameter("i_Register_Date", i_Register_Date) :
                new ObjectParameter("i_Register_Date", typeof(string));
    
            var i_Current_IterationParameter = i_Current_Iteration != null ?
                new ObjectParameter("i_Current_Iteration", i_Current_Iteration) :
                new ObjectParameter("i_Current_Iteration", typeof(string));
    
            var i_Customer_IDParameter = i_Customer_ID != null ?
                new ObjectParameter("i_Customer_ID", i_Customer_ID) :
                new ObjectParameter("i_Customer_ID", typeof(string));
    
            var i_Contractor_IDParameter = i_Contractor_ID != null ?
                new ObjectParameter("i_Contractor_ID", i_Contractor_ID) :
                new ObjectParameter("i_Contractor_ID", typeof(string));
    
            var i_SubContractor_IDParameter = i_SubContractor_ID != null ?
                new ObjectParameter("i_SubContractor_ID", i_SubContractor_ID) :
                new ObjectParameter("i_SubContractor_ID", typeof(string));
    
            var i_Resp_Employee_IDParameter = i_Resp_Employee_ID != null ?
                new ObjectParameter("i_Resp_Employee_ID", i_Resp_Employee_ID) :
                new ObjectParameter("i_Resp_Employee_ID", typeof(string));
    
            var i_WorkPackage_IDParameter = i_WorkPackage_ID != null ?
                new ObjectParameter("i_WorkPackage_ID", i_WorkPackage_ID) :
                new ObjectParameter("i_WorkPackage_ID", typeof(string));
    
            var i_CommentParameter = i_Comment != null ?
                new ObjectParameter("i_Comment", i_Comment) :
                new ObjectParameter("i_Comment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Register_Update_Result>("Register_Update", i_Register_IDParameter, i_RowStatusParameter, i_AppUser_IDParameter, i_Register_CodeParameter, i_Register_DateParameter, i_Current_IterationParameter, i_Customer_IDParameter, i_Contractor_IDParameter, i_SubContractor_IDParameter, i_Resp_Employee_IDParameter, i_WorkPackage_IDParameter, i_CommentParameter, o_IsError);
        }
    
        public virtual ObjectResult<Nullable<long>> Document_SequenceNumber()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("Document_SequenceNumber");
        }
    
        public virtual ObjectResult<Document_to_GOST_Delete_Result> Document_to_GOST_Delete(string i_AppUser_ID, string i_Document_to_GOST_ID, ObjectParameter o_IsError)
        {
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Document_to_GOST_IDParameter = i_Document_to_GOST_ID != null ?
                new ObjectParameter("i_Document_to_GOST_ID", i_Document_to_GOST_ID) :
                new ObjectParameter("i_Document_to_GOST_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Document_to_GOST_Delete_Result>("Document_to_GOST_Delete", i_AppUser_IDParameter, i_Document_to_GOST_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<Document_to_GOST_Insert_Result> Document_to_GOST_Insert(string i_RowStatus, string i_AppUser_ID, string i_Document_ID, string i_GOST_ID, ObjectParameter o_Entity_ID, ObjectParameter o_IsError)
        {
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Document_IDParameter = i_Document_ID != null ?
                new ObjectParameter("i_Document_ID", i_Document_ID) :
                new ObjectParameter("i_Document_ID", typeof(string));
    
            var i_GOST_IDParameter = i_GOST_ID != null ?
                new ObjectParameter("i_GOST_ID", i_GOST_ID) :
                new ObjectParameter("i_GOST_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Document_to_GOST_Insert_Result>("Document_to_GOST_Insert", i_RowStatusParameter, i_AppUser_IDParameter, i_Document_IDParameter, i_GOST_IDParameter, o_Entity_ID, o_IsError);
        }
    
        public virtual ObjectResult<Document_to_GOST_Update_Result> Document_to_GOST_Update(string i_Document_to_GOST_ID, string i_RowStatus, string i_AppUser_ID, string i_Document_ID, string i_GOST_ID, ObjectParameter o_IsError)
        {
            var i_Document_to_GOST_IDParameter = i_Document_to_GOST_ID != null ?
                new ObjectParameter("i_Document_to_GOST_ID", i_Document_to_GOST_ID) :
                new ObjectParameter("i_Document_to_GOST_ID", typeof(string));
    
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Document_IDParameter = i_Document_ID != null ?
                new ObjectParameter("i_Document_ID", i_Document_ID) :
                new ObjectParameter("i_Document_ID", typeof(string));
    
            var i_GOST_IDParameter = i_GOST_ID != null ?
                new ObjectParameter("i_GOST_ID", i_GOST_ID) :
                new ObjectParameter("i_GOST_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Document_to_GOST_Update_Result>("Document_to_GOST_Update", i_Document_to_GOST_IDParameter, i_RowStatusParameter, i_AppUser_IDParameter, i_Document_IDParameter, i_GOST_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<Document_to_PID_Delete_Result> Document_to_PID_Delete(string i_AppUser_ID, string i_Document_to_PID_ID, ObjectParameter o_IsError)
        {
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Document_to_PID_IDParameter = i_Document_to_PID_ID != null ?
                new ObjectParameter("i_Document_to_PID_ID", i_Document_to_PID_ID) :
                new ObjectParameter("i_Document_to_PID_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Document_to_PID_Delete_Result>("Document_to_PID_Delete", i_AppUser_IDParameter, i_Document_to_PID_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<Document_to_PID_Insert_Result> Document_to_PID_Insert(string i_RowStatus, string i_AppUser_ID, string i_Document_ID, string i_PID_ID, ObjectParameter o_Entity_ID, ObjectParameter o_IsError)
        {
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Document_IDParameter = i_Document_ID != null ?
                new ObjectParameter("i_Document_ID", i_Document_ID) :
                new ObjectParameter("i_Document_ID", typeof(string));
    
            var i_PID_IDParameter = i_PID_ID != null ?
                new ObjectParameter("i_PID_ID", i_PID_ID) :
                new ObjectParameter("i_PID_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Document_to_PID_Insert_Result>("Document_to_PID_Insert", i_RowStatusParameter, i_AppUser_IDParameter, i_Document_IDParameter, i_PID_IDParameter, o_Entity_ID, o_IsError);
        }
    
        public virtual ObjectResult<Document_to_PID_Update_Result> Document_to_PID_Update(string i_Document_to_PID_ID, string i_RowStatus, string i_AppUser_ID, string i_Document_ID, string i_PID_ID, ObjectParameter o_IsError)
        {
            var i_Document_to_PID_IDParameter = i_Document_to_PID_ID != null ?
                new ObjectParameter("i_Document_to_PID_ID", i_Document_to_PID_ID) :
                new ObjectParameter("i_Document_to_PID_ID", typeof(string));
    
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Document_IDParameter = i_Document_ID != null ?
                new ObjectParameter("i_Document_ID", i_Document_ID) :
                new ObjectParameter("i_Document_ID", typeof(string));
    
            var i_PID_IDParameter = i_PID_ID != null ?
                new ObjectParameter("i_PID_ID", i_PID_ID) :
                new ObjectParameter("i_PID_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Document_to_PID_Update_Result>("Document_to_PID_Update", i_Document_to_PID_IDParameter, i_RowStatusParameter, i_AppUser_IDParameter, i_Document_IDParameter, i_PID_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<Document_to_Status_Delete_Result> Document_to_Status_Delete(string i_AppUser_ID, string i_Document_to_Status_ID, ObjectParameter o_IsError)
        {
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Document_to_Status_IDParameter = i_Document_to_Status_ID != null ?
                new ObjectParameter("i_Document_to_Status_ID", i_Document_to_Status_ID) :
                new ObjectParameter("i_Document_to_Status_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Document_to_Status_Delete_Result>("Document_to_Status_Delete", i_AppUser_IDParameter, i_Document_to_Status_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<Document_to_Status_Insert_Result> Document_to_Status_Insert(string i_RowStatus, string i_AppUser_ID, string i_Document_ID, string i_Status_ID, string i_Parent_ID, ObjectParameter o_Entity_ID, ObjectParameter o_IsError)
        {
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Document_IDParameter = i_Document_ID != null ?
                new ObjectParameter("i_Document_ID", i_Document_ID) :
                new ObjectParameter("i_Document_ID", typeof(string));
    
            var i_Status_IDParameter = i_Status_ID != null ?
                new ObjectParameter("i_Status_ID", i_Status_ID) :
                new ObjectParameter("i_Status_ID", typeof(string));
    
            var i_Parent_IDParameter = i_Parent_ID != null ?
                new ObjectParameter("i_Parent_ID", i_Parent_ID) :
                new ObjectParameter("i_Parent_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Document_to_Status_Insert_Result>("Document_to_Status_Insert", i_RowStatusParameter, i_AppUser_IDParameter, i_Document_IDParameter, i_Status_IDParameter, i_Parent_IDParameter, o_Entity_ID, o_IsError);
        }
    
        public virtual ObjectResult<Document_to_Status_Update_Result> Document_to_Status_Update(string i_Document_to_Status_ID, string i_RowStatus, string i_AppUser_ID, string i_Document_ID, string i_Status_ID, ObjectParameter o_IsError)
        {
            var i_Document_to_Status_IDParameter = i_Document_to_Status_ID != null ?
                new ObjectParameter("i_Document_to_Status_ID", i_Document_to_Status_ID) :
                new ObjectParameter("i_Document_to_Status_ID", typeof(string));
    
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Document_IDParameter = i_Document_ID != null ?
                new ObjectParameter("i_Document_ID", i_Document_ID) :
                new ObjectParameter("i_Document_ID", typeof(string));
    
            var i_Status_IDParameter = i_Status_ID != null ?
                new ObjectParameter("i_Status_ID", i_Status_ID) :
                new ObjectParameter("i_Status_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Document_to_Status_Update_Result>("Document_to_Status_Update", i_Document_to_Status_IDParameter, i_RowStatusParameter, i_AppUser_IDParameter, i_Document_IDParameter, i_Status_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<Register_to_Marka_Delete_Result> Register_to_Marka_Delete(string i_AppUser_ID, string i_Register_to_Marka_ID, ObjectParameter o_IsError)
        {
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Register_to_Marka_IDParameter = i_Register_to_Marka_ID != null ?
                new ObjectParameter("i_Register_to_Marka_ID", i_Register_to_Marka_ID) :
                new ObjectParameter("i_Register_to_Marka_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Register_to_Marka_Delete_Result>("Register_to_Marka_Delete", i_AppUser_IDParameter, i_Register_to_Marka_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<Register_to_Marka_Insert_Result> Register_to_Marka_Insert(string i_RowStatus, string i_AppUser_ID, string i_Register_ID, string i_Marka_ID, string i_Iteration, ObjectParameter o_Entity_ID, ObjectParameter o_IsError)
        {
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Register_IDParameter = i_Register_ID != null ?
                new ObjectParameter("i_Register_ID", i_Register_ID) :
                new ObjectParameter("i_Register_ID", typeof(string));
    
            var i_Marka_IDParameter = i_Marka_ID != null ?
                new ObjectParameter("i_Marka_ID", i_Marka_ID) :
                new ObjectParameter("i_Marka_ID", typeof(string));
    
            var i_IterationParameter = i_Iteration != null ?
                new ObjectParameter("i_Iteration", i_Iteration) :
                new ObjectParameter("i_Iteration", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Register_to_Marka_Insert_Result>("Register_to_Marka_Insert", i_RowStatusParameter, i_AppUser_IDParameter, i_Register_IDParameter, i_Marka_IDParameter, i_IterationParameter, o_Entity_ID, o_IsError);
        }
    
        public virtual ObjectResult<Register_to_Marka_Update_Result> Register_to_Marka_Update(string i_Register_to_Marka_ID, string i_RowStatus, string i_AppUser_ID, string i_Register_ID, string i_Marka_ID, string i_Iteration, ObjectParameter o_IsError)
        {
            var i_Register_to_Marka_IDParameter = i_Register_to_Marka_ID != null ?
                new ObjectParameter("i_Register_to_Marka_ID", i_Register_to_Marka_ID) :
                new ObjectParameter("i_Register_to_Marka_ID", typeof(string));
    
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Register_IDParameter = i_Register_ID != null ?
                new ObjectParameter("i_Register_ID", i_Register_ID) :
                new ObjectParameter("i_Register_ID", typeof(string));
    
            var i_Marka_IDParameter = i_Marka_ID != null ?
                new ObjectParameter("i_Marka_ID", i_Marka_ID) :
                new ObjectParameter("i_Marka_ID", typeof(string));
    
            var i_IterationParameter = i_Iteration != null ?
                new ObjectParameter("i_Iteration", i_Iteration) :
                new ObjectParameter("i_Iteration", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Register_to_Marka_Update_Result>("Register_to_Marka_Update", i_Register_to_Marka_IDParameter, i_RowStatusParameter, i_AppUser_IDParameter, i_Register_IDParameter, i_Marka_IDParameter, i_IterationParameter, o_IsError);
        }
    
        public virtual ObjectResult<Register_to_TitleObject_Delete_Result> Register_to_TitleObject_Delete(string i_AppUser_ID, string i_Register_to_TitleObject_ID, ObjectParameter o_IsError)
        {
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Register_to_TitleObject_IDParameter = i_Register_to_TitleObject_ID != null ?
                new ObjectParameter("i_Register_to_TitleObject_ID", i_Register_to_TitleObject_ID) :
                new ObjectParameter("i_Register_to_TitleObject_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Register_to_TitleObject_Delete_Result>("Register_to_TitleObject_Delete", i_AppUser_IDParameter, i_Register_to_TitleObject_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<Register_to_TitleObject_Insert_Result> Register_to_TitleObject_Insert(string i_RowStatus, string i_AppUser_ID, string i_Register_ID, string i_TitleObject_ID, string i_Iteration, ObjectParameter o_Entity_ID, ObjectParameter o_IsError)
        {
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Register_IDParameter = i_Register_ID != null ?
                new ObjectParameter("i_Register_ID", i_Register_ID) :
                new ObjectParameter("i_Register_ID", typeof(string));
    
            var i_TitleObject_IDParameter = i_TitleObject_ID != null ?
                new ObjectParameter("i_TitleObject_ID", i_TitleObject_ID) :
                new ObjectParameter("i_TitleObject_ID", typeof(string));
    
            var i_IterationParameter = i_Iteration != null ?
                new ObjectParameter("i_Iteration", i_Iteration) :
                new ObjectParameter("i_Iteration", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Register_to_TitleObject_Insert_Result>("Register_to_TitleObject_Insert", i_RowStatusParameter, i_AppUser_IDParameter, i_Register_IDParameter, i_TitleObject_IDParameter, i_IterationParameter, o_Entity_ID, o_IsError);
        }
    
        public virtual ObjectResult<Register_to_TitleObject_Update_Result> Register_to_TitleObject_Update(string i_Register_to_TitleObject_ID, string i_RowStatus, string i_AppUser_ID, string i_Register_ID, string i_TitleObject_ID, string i_Iteration, ObjectParameter o_IsError)
        {
            var i_Register_to_TitleObject_IDParameter = i_Register_to_TitleObject_ID != null ?
                new ObjectParameter("i_Register_to_TitleObject_ID", i_Register_to_TitleObject_ID) :
                new ObjectParameter("i_Register_to_TitleObject_ID", typeof(string));
    
            var i_RowStatusParameter = i_RowStatus != null ?
                new ObjectParameter("i_RowStatus", i_RowStatus) :
                new ObjectParameter("i_RowStatus", typeof(string));
    
            var i_AppUser_IDParameter = i_AppUser_ID != null ?
                new ObjectParameter("i_AppUser_ID", i_AppUser_ID) :
                new ObjectParameter("i_AppUser_ID", typeof(string));
    
            var i_Register_IDParameter = i_Register_ID != null ?
                new ObjectParameter("i_Register_ID", i_Register_ID) :
                new ObjectParameter("i_Register_ID", typeof(string));
    
            var i_TitleObject_IDParameter = i_TitleObject_ID != null ?
                new ObjectParameter("i_TitleObject_ID", i_TitleObject_ID) :
                new ObjectParameter("i_TitleObject_ID", typeof(string));
    
            var i_IterationParameter = i_Iteration != null ?
                new ObjectParameter("i_Iteration", i_Iteration) :
                new ObjectParameter("i_Iteration", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Register_to_TitleObject_Update_Result>("Register_to_TitleObject_Update", i_Register_to_TitleObject_IDParameter, i_RowStatusParameter, i_AppUser_IDParameter, i_Register_IDParameter, i_TitleObject_IDParameter, i_IterationParameter, o_IsError);
        }
    }
}
