//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.WebDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CheckList
    {
        public System.Guid CheckList_ID { get; set; }
        public System.Guid Status_ID { get; set; }
        public string Status_Code { get; set; }
        public string Description_Rus { get; set; }
    }
}
