//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.WebDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UI_CheckItem
    {
        public string CheckList_Code { get; set; }
        public string CheckItem_Name { get; set; }
        public string Comment { get; set; }
        public string ShortName { get; set; }
        public string Position_Code { get; set; }
        public Nullable<System.Guid> Status_ID { get; set; }
        public string CheckItem_Status { get; set; }
        public System.DateTime Update_DTS { get; set; }
        public int Position { get; set; }
        public System.Guid CheckList_ID { get; set; }
        public System.Guid CheckItem_ID { get; set; }
        public string Division_Name { get; set; }
        public Nullable<System.Guid> Document_ID { get; set; }
        public string Document_Name { get; set; }
        public System.Guid Register_ID { get; set; }
        public string Document_Number { get; set; }
        public Nullable<System.DateTime> Issued_Date { get; set; }
        public string Status_Code { get; set; }
    }
}
