//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.WebDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UI_CheckResp
    {
        public System.Guid Register_ID { get; set; }
        public System.Guid CheckType_ID { get; set; }
        public string CheckType_Code { get; set; }
        public System.Guid Contragent_ID { get; set; }
        public string CheckParty_Name { get; set; }
        public Nullable<System.Guid> Position_ID { get; set; }
        public string Position_Description { get; set; }
        public Nullable<System.Guid> Person_ID { get; set; }
        public string CheckList_Resp_Shortname { get; set; }
        public System.Guid Status_ID { get; set; }
        public string checkList_Status { get; set; }
        public string CheckType_Description { get; set; }
        public System.Guid CheckList_ID { get; set; }
        public Nullable<System.Guid> CheckResp_ID { get; set; }
    }
}
