//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.WebDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UI_CheckList
    {
        public string CheckList_Code { get; set; }
        public System.DateTime CheckList_Date { get; set; }
        public string CheckParty_Code { get; set; }
        public string Position_Description { get; set; }
        public string ShortName { get; set; }
        public string CheckList_Status { get; set; }
        public System.Guid Register_ID { get; set; }
        public System.Guid CheckList_ID { get; set; }
        public string Status_Code { get; set; }
        public System.Guid Status_ID { get; set; }
        public Nullable<System.Guid> Position_ID { get; set; }
        public Nullable<System.Guid> Person_ID { get; set; }
        public Nullable<System.Guid> CheckType_ID { get; set; }
        public string CheckType_Code { get; set; }
    }
}
