//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.WebDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UI_FileStream
    {
        public System.Guid Document_ID { get; set; }
        public System.Guid FileTable_ID { get; set; }
        public string name { get; set; }
        public string file_type { get; set; }
        public Nullable<System.DateTime> last_write_time { get; set; }
        public System.Guid Document_to_FileTable_ID { get; set; }
    }
}
