//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.WebDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UI_Register_ListItem
    {
        public System.Guid Register_ID { get; set; }
        public string Register_Code { get; set; }
        public System.DateTime Register_Date { get; set; }
        public int Register_Iteration { get; set; }
        public System.Guid Document_ID { get; set; }
        public string Document_Code { get; set; }
        public string Document_Name { get; set; }
        public Nullable<System.DateTime> Document_Date { get; set; }
        public string Document_Number { get; set; }
        public Nullable<System.DateTime> Document_Issue_Date { get; set; }
        public int Document_Iteration { get; set; }
        public Nullable<int> Document_Position { get; set; }
        public Nullable<int> Document_SheetNumber { get; set; }
        public string Document_Comment { get; set; }
        public System.Guid Register_to_Document_ID { get; set; }
    }
}
