//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.WebDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UI_Register_List
    {
        public System.Guid Register_ID { get; set; }
        public string Register_Code { get; set; }
        public System.DateTime Register_Date { get; set; }
        public int Current_Iteration { get; set; }
        public Nullable<System.Guid> Status_ID { get; set; }
        public string Status_Code { get; set; }
        public string Status_Description_Rus { get; set; }
        public Nullable<System.Guid> Contractor_ID { get; set; }
        public string Contractor_Code { get; set; }
        public Nullable<System.Guid> SubContractor_ID { get; set; }
        public string SubContractor_Code { get; set; }
        public Nullable<System.Guid> Customer_ID { get; set; }
        public string Customer_Code { get; set; }
        public Nullable<System.Guid> TitleObject_ID { get; set; }
        public string TitleObject_Code { get; set; }
        public Nullable<System.Guid> Marka_ID { get; set; }
        public string Marka_Code { get; set; }
        public string Complex { get; set; }
        public string Project { get; set; }
        public int UI_PageNumber { get; set; }
        public Nullable<System.Guid> WorkPackage_ID { get; set; }
        public string WorkPackage_Code { get; set; }
    }
}
