//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.WebDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UI_StatusRelation
    {
        public System.Guid FromStatus_ID { get; set; }
        public string FromStatus { get; set; }
        public System.Guid ToStatus_ID { get; set; }
        public string ToStatus { get; set; }
        public Nullable<int> IterationIncrement { get; set; }
    }
}
