//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.Logging
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserTaskMessage
    {
        public System.Guid AppUserTaskMessage_ID { get; set; }
        public int AppUserTaskMessage_Code { get; set; }
        public int Message_Type { get; set; }
        public string Message_Text { get; set; }
        public string MessageDescription_ENG { get; set; }
        public string MessageDescription_RUS { get; set; }
    }
}
