//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.Logging
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public System.Guid Role_ID { get; set; }
        public string Role_Code { get; set; }
    }
}
