//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.PermissionDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentAttribute
    {
        public System.Guid DocumentAttribute_ID { get; set; }
        public string DocumentAttribute_Value { get; set; }
        public System.Guid AttributeType_ID { get; set; }
        public System.Guid Document_ID { get; set; }
        public int DocumentAttribute_Order { get; set; }
    
        public virtual EAVDocument Document { get; set; }
        public virtual AttributeType AttributeType { get; set; }
    }
}
