//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.PermissionDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentRelation
    {
        public System.Guid DocumentRelation_ID { get; set; }
        public System.Guid DocumentFrom_ID { get; set; }
        public System.Guid DocumentTo_ID { get; set; }
        public System.Guid RelationType_ID { get; set; }
        public int DocumentRelation_Order { get; set; }
    
        public virtual EAVDocument DocumentTo { get; set; }
        public virtual EAVDocument DocumentFrom { get; set; }
    }
}
