//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.PermissionDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAVDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EAVDocument()
        {
            this.DocumentAttributes = new HashSet<DocumentAttribute>();
            this.DocumentRelationsFrom = new HashSet<DocumentRelation>();
            this.DocumentRelationsTo = new HashSet<DocumentRelation>();
        }
    
        public System.Guid Document_ID { get; set; }
        public string Document_Name { get; set; }
        public string Document_Title { get; set; }
        public System.Guid DocumentType_ID { get; set; }
        public string Document_Revision { get; set; }
        public Nullable<System.Guid> Document_Parent_ID { get; set; }
        public Nullable<System.Guid> Reponsible_Employee_ID { get; set; }
        public string Document_Number { get; set; }
        public Nullable<System.DateTime> Document_Date { get; set; }
    
        public virtual EAVDocumentType DocumentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentAttribute> DocumentAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentRelation> DocumentRelationsFrom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentRelation> DocumentRelationsTo { get; set; }
    }
}
