//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.PermissionDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAVDocumentType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EAVDocumentType()
        {
            this.Documents = new HashSet<EAVDocument>();
        }
    
        public System.Guid DocumentType_ID { get; set; }
        public string DocumentType_Code { get; set; }
        public string DocumentType_Name { get; set; }
        public string DocumentType_Group { get; set; }
        public string Description_Rus { get; set; }
        public string Description_Eng { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EAVDocument> Documents { get; set; }
    }
}
