//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.PermissionDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UI_Contragent
    {
        public System.Guid Contragent_ID { get; set; }
        public string Contragent_Code { get; set; }
        public string Description_Eng { get; set; }
        public string Description_Rus { get; set; }
    }
}
