//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.PermissionDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UI_Personal
    {
        public System.Guid Employee_ID { get; set; }
        public string Employee_Code { get; set; }
        public Nullable<System.Guid> Person_ID { get; set; }
        public string Person_Code { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string LastName { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public Nullable<System.Guid> Position_ID { get; set; }
        public string Position_Code { get; set; }
        public string Position_Description { get; set; }
        public Nullable<System.Guid> AppUser_ID { get; set; }
        public string AppUser_Code { get; set; }
        public Nullable<System.Guid> Division_ID { get; set; }
        public string Division_Code { get; set; }
        public Nullable<System.Guid> Contragent_ID { get; set; }
        public string Contragent_Code { get; set; }
        public string Description_Rus { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
    }
}
