//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABDDocumentFull
    {
        public System.Guid ABDDocument_ID { get; set; }
        public string ABDDocument_Number { get; set; }
        public string ABDDocument_Name { get; set; }
        public Nullable<System.Guid> ABDFinalFolder_ID { get; set; }
        public string ABDFinalFolder_Name { get; set; }
        public Nullable<System.Guid> DisciplineDocumentCode_ID { get; set; }
        public string DisciplineDocumentCode_Name { get; set; }
        public string DDC_Description_Rus { get; set; }
        public string DDC_Description_Eng { get; set; }
        public Nullable<System.Guid> DocumentTypeCode_ID { get; set; }
        public string DocumentTypeCode_Name { get; set; }
        public string DTC_Description_Rus { get; set; }
        public string DTC_Description_Eng { get; set; }
        public Nullable<System.Guid> GOST_ID { get; set; }
        public string GOST_Code { get; set; }
        public string G_Description_Rus { get; set; }
        public Nullable<System.Guid> Module_ID { get; set; }
        public string Module_Name { get; set; }
        public string M_Description_Rus { get; set; }
        public string M_Description_Eng { get; set; }
        public Nullable<System.Guid> PID_ID { get; set; }
        public string PID_Code { get; set; }
        public string PID_Description_Eng { get; set; }
        public Nullable<System.Guid> SubContractor_ID { get; set; }
        public string SubContractor_Name { get; set; }
        public Nullable<System.Guid> UnitNumberDocumentCode_ID { get; set; }
        public string UnitNumberDocumentCode_Name { get; set; }
        public string U_Description_Rus { get; set; }
        public string U_Description_Eng { get; set; }
        public System.DateTime Issue_Date { get; set; }
        public int Sheet_Folder_Number { get; set; }
        public int Total_Sheets { get; set; }
        public int Number_in_Folder { get; set; }
        public string Structure { get; set; }
        public Nullable<System.Guid> Structure_ID { get; set; }
        public Nullable<System.DateTime> Final_Compilation_Target_Date { get; set; }
        public Nullable<System.DateTime> Final_Compilation_Start_Date { get; set; }
        public string CTR_RESP { get; set; }
        public System.Guid ABDDocumentFull_ID { get; set; }
        public string Modified_User { get; set; }
        public string Created_User { get; set; }
    }
}
