//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalABDCompilation
    {
        public System.Guid ABDFinalFolder_ID { get; set; }
        public string ABDFinalFolder_Name { get; set; }
        public string CTR_RESP { get; set; }
        public Nullable<System.DateTime> Final_Compilation_Start_Date { get; set; }
        public Nullable<System.DateTime> Final_Compilation_Target_Date { get; set; }
        public Nullable<int> ListCount { get; set; }
        public System.Guid ABDFinalSet_ID { get; set; }
        public string ABDFinalSet_Number { get; set; }
        public System.Guid ABDStatus_ID { get; set; }
        public string Status_ENG { get; set; }
        public string Status_Rus { get; set; }
        public System.Guid TitleObject_ID { get; set; }
        public string TitleObject_Name { get; set; }
        public System.Guid SubContractor_Id { get; set; }
        public string SubContractor_Name { get; set; }
        public System.Guid Marka_ID { get; set; }
        public string Marka_Name { get; set; }
        public Nullable<System.Guid> Transmittal_ID { get; set; }
        public string Transmittal_Code { get; set; }
        public string ReportColor { get; set; }
        public Nullable<int> ReportOrder { get; set; }
        public string FoldedStatus { get; set; }
        public System.Guid NewGUID { get; set; }
    }
}
