//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_ABDFinalFolder_to_Contragent
    {
        public System.Guid ABDFinalFolder_to_Contragent_ID { get; set; }
        public Nullable<System.DateTime> Insert_DTS { get; set; }
        public Nullable<System.DateTime> Update_DTS { get; set; }
        public Nullable<int> Row_Status { get; set; }
        public System.Guid ABDFinalFolder_ID { get; set; }
        public System.Guid Contragent_ID { get; set; }
    
        public virtual p_ABDFinalFolder p_ABDFinalFolder { get; set; }
        public virtual p_Contragent p_Contragent { get; set; }
    }
}
