//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_ABDStatus
    {
        public System.Guid ABDStatus_ID { get; set; }
        public string Stage { get; set; }
        public string Code { get; set; }
        public string Description_Eng { get; set; }
        public string Description_Rus { get; set; }
        public Nullable<int> Status_Type { get; set; }
        public Nullable<int> Row_status { get; set; }
        public Nullable<System.DateTime> Insert_DTS { get; set; }
        public Nullable<System.DateTime> Update_DTS { get; set; }
        public string ReportColor { get; set; }
        public Nullable<int> ReportOrder { get; set; }
    }
}
