//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Register_to_Status
    {
        public System.Guid Register_To_Status_ID { get; set; }
        public Nullable<System.Guid> Parent_ID { get; set; }
        public Nullable<System.DateTime> DTS_Start { get; set; }
        public Nullable<System.DateTime> DTS_End { get; set; }
        public Nullable<int> Row_status { get; set; }
        public System.Guid Register_ID { get; set; }
        public System.Guid ABDStatus_ID { get; set; }
        public Nullable<System.DateTime> Insert_DTS { get; set; }
        public Nullable<System.DateTime> Update_DTS { get; set; }
        public Nullable<System.DateTime> ABDStatusDate { get; set; }
        public Nullable<System.Guid> Created_User_ID { get; set; }
        public Nullable<System.Guid> Modified_User_ID { get; set; }
    
        public virtual p_ABDStatus p_ABDStatus { get; set; }
    }
}
