//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<p_ABDStatus> p_ABDStatus { get; set; }
        public virtual DbSet<Phase> Phases { get; set; }
        public virtual DbSet<ProcessPhase> ProcessPhases { get; set; }
        public virtual DbSet<UI_RegisterList> UI_RegisterList { get; set; }
        public virtual DbSet<UI_TitleObject_to_Phase> UI_TitleObject_to_Phase { get; set; }
        public virtual DbSet<UI_Marka> UI_Marka { get; set; }
        public virtual DbSet<UI_TitleObject> UI_TitleObject { get; set; }
        public virtual DbSet<p_ABDFinalFolder> p_ABDFinalFolder { get; set; }
        public virtual DbSet<p_ABDFinalFolder_to_Contragent> p_ABDFinalFolder_to_Contragent { get; set; }
        public virtual DbSet<p_Contragent> p_Contragent { get; set; }
        public virtual DbSet<R_Structure> R_Structure { get; set; }
        public virtual DbSet<FinalABDCompilation> FinalABDCompilations { get; set; }
        public virtual DbSet<UI_ISO> UI_ISO { get; set; }
        public virtual DbSet<UI_Line> UI_Line { get; set; }
        public virtual DbSet<DesignAreaType> DesignAreaTypes { get; set; }
        public virtual DbSet<ABDDocument_to_FileTable_StreamFull> ABDDocument_to_FileTable_StreamFull { get; set; }
        public virtual DbSet<ABDDocumentFull> ABDDocumentFulls { get; set; }
    
        public virtual ObjectResult<Line_Delete_Result> Line_Delete(string i_User_ID, string i_Line_ID, ObjectParameter o_IsError)
        {
            var i_User_IDParameter = i_User_ID != null ?
                new ObjectParameter("i_User_ID", i_User_ID) :
                new ObjectParameter("i_User_ID", typeof(string));
    
            var i_Line_IDParameter = i_Line_ID != null ?
                new ObjectParameter("i_Line_ID", i_Line_ID) :
                new ObjectParameter("i_Line_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Line_Delete_Result>("Line_Delete", i_User_IDParameter, i_Line_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<Line_Insert_Result> Line_Insert(string i_Row_Status, string i_User_ID, string i_Line_Number, string i_Location_From, string i_Location_To, string i_Fluid_Name_Eng, string i_Fluid_Name_Rus, string i_Fluid_Danger_Code_By_Gost, string i_Fluid_Fire_Aand_Explosive_Hazard, string i_Fluid_Group_By_TP_TC_032_2013, string i_Fluid_Group_By_GOST_32569_2013, string i_Pipeline_Category_By_GOST_32569_2013, string i_Piprline_Category_By_TP_TC_032_2013, ObjectParameter o_Entity_ID, ObjectParameter o_IsError)
        {
            var i_Row_StatusParameter = i_Row_Status != null ?
                new ObjectParameter("i_Row_Status", i_Row_Status) :
                new ObjectParameter("i_Row_Status", typeof(string));
    
            var i_User_IDParameter = i_User_ID != null ?
                new ObjectParameter("i_User_ID", i_User_ID) :
                new ObjectParameter("i_User_ID", typeof(string));
    
            var i_Line_NumberParameter = i_Line_Number != null ?
                new ObjectParameter("i_Line_Number", i_Line_Number) :
                new ObjectParameter("i_Line_Number", typeof(string));
    
            var i_Location_FromParameter = i_Location_From != null ?
                new ObjectParameter("i_Location_From", i_Location_From) :
                new ObjectParameter("i_Location_From", typeof(string));
    
            var i_Location_ToParameter = i_Location_To != null ?
                new ObjectParameter("i_Location_To", i_Location_To) :
                new ObjectParameter("i_Location_To", typeof(string));
    
            var i_Fluid_Name_EngParameter = i_Fluid_Name_Eng != null ?
                new ObjectParameter("i_Fluid_Name_Eng", i_Fluid_Name_Eng) :
                new ObjectParameter("i_Fluid_Name_Eng", typeof(string));
    
            var i_Fluid_Name_RusParameter = i_Fluid_Name_Rus != null ?
                new ObjectParameter("i_Fluid_Name_Rus", i_Fluid_Name_Rus) :
                new ObjectParameter("i_Fluid_Name_Rus", typeof(string));
    
            var i_Fluid_Danger_Code_By_GostParameter = i_Fluid_Danger_Code_By_Gost != null ?
                new ObjectParameter("i_Fluid_Danger_Code_By_Gost", i_Fluid_Danger_Code_By_Gost) :
                new ObjectParameter("i_Fluid_Danger_Code_By_Gost", typeof(string));
    
            var i_Fluid_Fire_Aand_Explosive_HazardParameter = i_Fluid_Fire_Aand_Explosive_Hazard != null ?
                new ObjectParameter("i_Fluid_Fire_Aand_Explosive_Hazard", i_Fluid_Fire_Aand_Explosive_Hazard) :
                new ObjectParameter("i_Fluid_Fire_Aand_Explosive_Hazard", typeof(string));
    
            var i_Fluid_Group_By_TP_TC_032_2013Parameter = i_Fluid_Group_By_TP_TC_032_2013 != null ?
                new ObjectParameter("i_Fluid_Group_By_TP_TC_032_2013", i_Fluid_Group_By_TP_TC_032_2013) :
                new ObjectParameter("i_Fluid_Group_By_TP_TC_032_2013", typeof(string));
    
            var i_Fluid_Group_By_GOST_32569_2013Parameter = i_Fluid_Group_By_GOST_32569_2013 != null ?
                new ObjectParameter("i_Fluid_Group_By_GOST_32569_2013", i_Fluid_Group_By_GOST_32569_2013) :
                new ObjectParameter("i_Fluid_Group_By_GOST_32569_2013", typeof(string));
    
            var i_Pipeline_Category_By_GOST_32569_2013Parameter = i_Pipeline_Category_By_GOST_32569_2013 != null ?
                new ObjectParameter("i_Pipeline_Category_By_GOST_32569_2013", i_Pipeline_Category_By_GOST_32569_2013) :
                new ObjectParameter("i_Pipeline_Category_By_GOST_32569_2013", typeof(string));
    
            var i_Piprline_Category_By_TP_TC_032_2013Parameter = i_Piprline_Category_By_TP_TC_032_2013 != null ?
                new ObjectParameter("i_Piprline_Category_By_TP_TC_032_2013", i_Piprline_Category_By_TP_TC_032_2013) :
                new ObjectParameter("i_Piprline_Category_By_TP_TC_032_2013", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Line_Insert_Result>("Line_Insert", i_Row_StatusParameter, i_User_IDParameter, i_Line_NumberParameter, i_Location_FromParameter, i_Location_ToParameter, i_Fluid_Name_EngParameter, i_Fluid_Name_RusParameter, i_Fluid_Danger_Code_By_GostParameter, i_Fluid_Fire_Aand_Explosive_HazardParameter, i_Fluid_Group_By_TP_TC_032_2013Parameter, i_Fluid_Group_By_GOST_32569_2013Parameter, i_Pipeline_Category_By_GOST_32569_2013Parameter, i_Piprline_Category_By_TP_TC_032_2013Parameter, o_Entity_ID, o_IsError);
        }
    
        public virtual ObjectResult<Line_Update_Result> Line_Update(string i_Line_ID, string i_Row_Status, string i_User_ID, string i_Line_Number, string i_Location_From, string i_Location_To, string i_Fluid_Name_Eng, string i_Fluid_Name_Rus, string i_Fluid_Danger_Code_By_Gost, string i_Fluid_Fire_Aand_Explosive_Hazard, string i_Fluid_Group_By_TP_TC_032_2013, string i_Fluid_Group_By_GOST_32569_2013, string i_Pipeline_Category_By_GOST_32569_2013, string i_Piprline_Category_By_TP_TC_032_2013, ObjectParameter o_IsError)
        {
            var i_Line_IDParameter = i_Line_ID != null ?
                new ObjectParameter("i_Line_ID", i_Line_ID) :
                new ObjectParameter("i_Line_ID", typeof(string));
    
            var i_Row_StatusParameter = i_Row_Status != null ?
                new ObjectParameter("i_Row_Status", i_Row_Status) :
                new ObjectParameter("i_Row_Status", typeof(string));
    
            var i_User_IDParameter = i_User_ID != null ?
                new ObjectParameter("i_User_ID", i_User_ID) :
                new ObjectParameter("i_User_ID", typeof(string));
    
            var i_Line_NumberParameter = i_Line_Number != null ?
                new ObjectParameter("i_Line_Number", i_Line_Number) :
                new ObjectParameter("i_Line_Number", typeof(string));
    
            var i_Location_FromParameter = i_Location_From != null ?
                new ObjectParameter("i_Location_From", i_Location_From) :
                new ObjectParameter("i_Location_From", typeof(string));
    
            var i_Location_ToParameter = i_Location_To != null ?
                new ObjectParameter("i_Location_To", i_Location_To) :
                new ObjectParameter("i_Location_To", typeof(string));
    
            var i_Fluid_Name_EngParameter = i_Fluid_Name_Eng != null ?
                new ObjectParameter("i_Fluid_Name_Eng", i_Fluid_Name_Eng) :
                new ObjectParameter("i_Fluid_Name_Eng", typeof(string));
    
            var i_Fluid_Name_RusParameter = i_Fluid_Name_Rus != null ?
                new ObjectParameter("i_Fluid_Name_Rus", i_Fluid_Name_Rus) :
                new ObjectParameter("i_Fluid_Name_Rus", typeof(string));
    
            var i_Fluid_Danger_Code_By_GostParameter = i_Fluid_Danger_Code_By_Gost != null ?
                new ObjectParameter("i_Fluid_Danger_Code_By_Gost", i_Fluid_Danger_Code_By_Gost) :
                new ObjectParameter("i_Fluid_Danger_Code_By_Gost", typeof(string));
    
            var i_Fluid_Fire_Aand_Explosive_HazardParameter = i_Fluid_Fire_Aand_Explosive_Hazard != null ?
                new ObjectParameter("i_Fluid_Fire_Aand_Explosive_Hazard", i_Fluid_Fire_Aand_Explosive_Hazard) :
                new ObjectParameter("i_Fluid_Fire_Aand_Explosive_Hazard", typeof(string));
    
            var i_Fluid_Group_By_TP_TC_032_2013Parameter = i_Fluid_Group_By_TP_TC_032_2013 != null ?
                new ObjectParameter("i_Fluid_Group_By_TP_TC_032_2013", i_Fluid_Group_By_TP_TC_032_2013) :
                new ObjectParameter("i_Fluid_Group_By_TP_TC_032_2013", typeof(string));
    
            var i_Fluid_Group_By_GOST_32569_2013Parameter = i_Fluid_Group_By_GOST_32569_2013 != null ?
                new ObjectParameter("i_Fluid_Group_By_GOST_32569_2013", i_Fluid_Group_By_GOST_32569_2013) :
                new ObjectParameter("i_Fluid_Group_By_GOST_32569_2013", typeof(string));
    
            var i_Pipeline_Category_By_GOST_32569_2013Parameter = i_Pipeline_Category_By_GOST_32569_2013 != null ?
                new ObjectParameter("i_Pipeline_Category_By_GOST_32569_2013", i_Pipeline_Category_By_GOST_32569_2013) :
                new ObjectParameter("i_Pipeline_Category_By_GOST_32569_2013", typeof(string));
    
            var i_Piprline_Category_By_TP_TC_032_2013Parameter = i_Piprline_Category_By_TP_TC_032_2013 != null ?
                new ObjectParameter("i_Piprline_Category_By_TP_TC_032_2013", i_Piprline_Category_By_TP_TC_032_2013) :
                new ObjectParameter("i_Piprline_Category_By_TP_TC_032_2013", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Line_Update_Result>("Line_Update", i_Line_IDParameter, i_Row_StatusParameter, i_User_IDParameter, i_Line_NumberParameter, i_Location_FromParameter, i_Location_ToParameter, i_Fluid_Name_EngParameter, i_Fluid_Name_RusParameter, i_Fluid_Danger_Code_By_GostParameter, i_Fluid_Fire_Aand_Explosive_HazardParameter, i_Fluid_Group_By_TP_TC_032_2013Parameter, i_Fluid_Group_By_GOST_32569_2013Parameter, i_Pipeline_Category_By_GOST_32569_2013Parameter, i_Piprline_Category_By_TP_TC_032_2013Parameter, o_IsError);
        }
    
        public virtual ObjectResult<ISO_Delete_Result> ISO_Delete(string i_ISO_ID, string i_User_ID, ObjectParameter o_IsError)
        {
            var i_ISO_IDParameter = i_ISO_ID != null ?
                new ObjectParameter("i_ISO_ID", i_ISO_ID) :
                new ObjectParameter("i_ISO_ID", typeof(string));
    
            var i_User_IDParameter = i_User_ID != null ?
                new ObjectParameter("i_User_ID", i_User_ID) :
                new ObjectParameter("i_User_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ISO_Delete_Result>("ISO_Delete", i_ISO_IDParameter, i_User_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<ISO_Insert_Result> ISO_Insert(string i_Row_Status, string i_User_ID, string i_ISO_Number, string i_Line_ID, string i_Phase_ID, string i_Marka_ID, string i_TitleObject_ID, string i_DesignAreaType_ID, string i_ProcessPhase_ID, ObjectParameter o_Entity_ID, ObjectParameter o_IsError)
        {
            var i_Row_StatusParameter = i_Row_Status != null ?
                new ObjectParameter("i_Row_Status", i_Row_Status) :
                new ObjectParameter("i_Row_Status", typeof(string));
    
            var i_User_IDParameter = i_User_ID != null ?
                new ObjectParameter("i_User_ID", i_User_ID) :
                new ObjectParameter("i_User_ID", typeof(string));
    
            var i_ISO_NumberParameter = i_ISO_Number != null ?
                new ObjectParameter("i_ISO_Number", i_ISO_Number) :
                new ObjectParameter("i_ISO_Number", typeof(string));
    
            var i_Line_IDParameter = i_Line_ID != null ?
                new ObjectParameter("i_Line_ID", i_Line_ID) :
                new ObjectParameter("i_Line_ID", typeof(string));
    
            var i_Phase_IDParameter = i_Phase_ID != null ?
                new ObjectParameter("i_Phase_ID", i_Phase_ID) :
                new ObjectParameter("i_Phase_ID", typeof(string));
    
            var i_Marka_IDParameter = i_Marka_ID != null ?
                new ObjectParameter("i_Marka_ID", i_Marka_ID) :
                new ObjectParameter("i_Marka_ID", typeof(string));
    
            var i_TitleObject_IDParameter = i_TitleObject_ID != null ?
                new ObjectParameter("i_TitleObject_ID", i_TitleObject_ID) :
                new ObjectParameter("i_TitleObject_ID", typeof(string));
    
            var i_DesignAreaType_IDParameter = i_DesignAreaType_ID != null ?
                new ObjectParameter("i_DesignAreaType_ID", i_DesignAreaType_ID) :
                new ObjectParameter("i_DesignAreaType_ID", typeof(string));
    
            var i_ProcessPhase_IDParameter = i_ProcessPhase_ID != null ?
                new ObjectParameter("i_ProcessPhase_ID", i_ProcessPhase_ID) :
                new ObjectParameter("i_ProcessPhase_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ISO_Insert_Result>("ISO_Insert", i_Row_StatusParameter, i_User_IDParameter, i_ISO_NumberParameter, i_Line_IDParameter, i_Phase_IDParameter, i_Marka_IDParameter, i_TitleObject_IDParameter, i_DesignAreaType_IDParameter, i_ProcessPhase_IDParameter, o_Entity_ID, o_IsError);
        }
    
        public virtual ObjectResult<ISO_Update_Result> ISO_Update(string i_ISO_ID, string i_Row_Status, string i_User_ID, string i_ISO_Number, string i_Line_ID, string i_Phase_ID, string i_Marka_ID, string i_TitleObject_ID, string i_DesignAreaType_ID, string i_ProcessPhase_ID, ObjectParameter o_IsError)
        {
            var i_ISO_IDParameter = i_ISO_ID != null ?
                new ObjectParameter("i_ISO_ID", i_ISO_ID) :
                new ObjectParameter("i_ISO_ID", typeof(string));
    
            var i_Row_StatusParameter = i_Row_Status != null ?
                new ObjectParameter("i_Row_Status", i_Row_Status) :
                new ObjectParameter("i_Row_Status", typeof(string));
    
            var i_User_IDParameter = i_User_ID != null ?
                new ObjectParameter("i_User_ID", i_User_ID) :
                new ObjectParameter("i_User_ID", typeof(string));
    
            var i_ISO_NumberParameter = i_ISO_Number != null ?
                new ObjectParameter("i_ISO_Number", i_ISO_Number) :
                new ObjectParameter("i_ISO_Number", typeof(string));
    
            var i_Line_IDParameter = i_Line_ID != null ?
                new ObjectParameter("i_Line_ID", i_Line_ID) :
                new ObjectParameter("i_Line_ID", typeof(string));
    
            var i_Phase_IDParameter = i_Phase_ID != null ?
                new ObjectParameter("i_Phase_ID", i_Phase_ID) :
                new ObjectParameter("i_Phase_ID", typeof(string));
    
            var i_Marka_IDParameter = i_Marka_ID != null ?
                new ObjectParameter("i_Marka_ID", i_Marka_ID) :
                new ObjectParameter("i_Marka_ID", typeof(string));
    
            var i_TitleObject_IDParameter = i_TitleObject_ID != null ?
                new ObjectParameter("i_TitleObject_ID", i_TitleObject_ID) :
                new ObjectParameter("i_TitleObject_ID", typeof(string));
    
            var i_DesignAreaType_IDParameter = i_DesignAreaType_ID != null ?
                new ObjectParameter("i_DesignAreaType_ID", i_DesignAreaType_ID) :
                new ObjectParameter("i_DesignAreaType_ID", typeof(string));
    
            var i_ProcessPhase_IDParameter = i_ProcessPhase_ID != null ?
                new ObjectParameter("i_ProcessPhase_ID", i_ProcessPhase_ID) :
                new ObjectParameter("i_ProcessPhase_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ISO_Update_Result>("ISO_Update", i_ISO_IDParameter, i_Row_StatusParameter, i_User_IDParameter, i_ISO_NumberParameter, i_Line_IDParameter, i_Phase_IDParameter, i_Marka_IDParameter, i_TitleObject_IDParameter, i_DesignAreaType_IDParameter, i_ProcessPhase_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<Marka_Delete_Result> Marka_Delete(string i_User_ID, string i_Marka_ID, ObjectParameter o_IsError)
        {
            var i_User_IDParameter = i_User_ID != null ?
                new ObjectParameter("i_User_ID", i_User_ID) :
                new ObjectParameter("i_User_ID", typeof(string));
    
            var i_Marka_IDParameter = i_Marka_ID != null ?
                new ObjectParameter("i_Marka_ID", i_Marka_ID) :
                new ObjectParameter("i_Marka_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Marka_Delete_Result>("Marka_Delete", i_User_IDParameter, i_Marka_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<Marka_Insert_Result> Marka_Insert(string i_Row_Status, string i_User_ID, string i_Marka_Name, string i_Code_of_mark, string i_Description_Eng, string i_Description_Rus, string i_Engineering_Drawing_Type_Eng, string i_Engineering_Drawing_Type_Rus, string i_IsUsedInMatrix, string i_IsPriority, string i_ReportColor, string i_ReportOrder, ObjectParameter o_Entity_ID, ObjectParameter o_IsError)
        {
            var i_Row_StatusParameter = i_Row_Status != null ?
                new ObjectParameter("i_Row_Status", i_Row_Status) :
                new ObjectParameter("i_Row_Status", typeof(string));
    
            var i_User_IDParameter = i_User_ID != null ?
                new ObjectParameter("i_User_ID", i_User_ID) :
                new ObjectParameter("i_User_ID", typeof(string));
    
            var i_Marka_NameParameter = i_Marka_Name != null ?
                new ObjectParameter("i_Marka_Name", i_Marka_Name) :
                new ObjectParameter("i_Marka_Name", typeof(string));
    
            var i_Code_of_markParameter = i_Code_of_mark != null ?
                new ObjectParameter("i_Code_of_mark", i_Code_of_mark) :
                new ObjectParameter("i_Code_of_mark", typeof(string));
    
            var i_Description_EngParameter = i_Description_Eng != null ?
                new ObjectParameter("i_Description_Eng", i_Description_Eng) :
                new ObjectParameter("i_Description_Eng", typeof(string));
    
            var i_Description_RusParameter = i_Description_Rus != null ?
                new ObjectParameter("i_Description_Rus", i_Description_Rus) :
                new ObjectParameter("i_Description_Rus", typeof(string));
    
            var i_Engineering_Drawing_Type_EngParameter = i_Engineering_Drawing_Type_Eng != null ?
                new ObjectParameter("i_Engineering_Drawing_Type_Eng", i_Engineering_Drawing_Type_Eng) :
                new ObjectParameter("i_Engineering_Drawing_Type_Eng", typeof(string));
    
            var i_Engineering_Drawing_Type_RusParameter = i_Engineering_Drawing_Type_Rus != null ?
                new ObjectParameter("i_Engineering_Drawing_Type_Rus", i_Engineering_Drawing_Type_Rus) :
                new ObjectParameter("i_Engineering_Drawing_Type_Rus", typeof(string));
    
            var i_IsUsedInMatrixParameter = i_IsUsedInMatrix != null ?
                new ObjectParameter("i_IsUsedInMatrix", i_IsUsedInMatrix) :
                new ObjectParameter("i_IsUsedInMatrix", typeof(string));
    
            var i_IsPriorityParameter = i_IsPriority != null ?
                new ObjectParameter("i_IsPriority", i_IsPriority) :
                new ObjectParameter("i_IsPriority", typeof(string));
    
            var i_ReportColorParameter = i_ReportColor != null ?
                new ObjectParameter("i_ReportColor", i_ReportColor) :
                new ObjectParameter("i_ReportColor", typeof(string));
    
            var i_ReportOrderParameter = i_ReportOrder != null ?
                new ObjectParameter("i_ReportOrder", i_ReportOrder) :
                new ObjectParameter("i_ReportOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Marka_Insert_Result>("Marka_Insert", i_Row_StatusParameter, i_User_IDParameter, i_Marka_NameParameter, i_Code_of_markParameter, i_Description_EngParameter, i_Description_RusParameter, i_Engineering_Drawing_Type_EngParameter, i_Engineering_Drawing_Type_RusParameter, i_IsUsedInMatrixParameter, i_IsPriorityParameter, i_ReportColorParameter, i_ReportOrderParameter, o_Entity_ID, o_IsError);
        }
    
        public virtual ObjectResult<Marka_Update_Result> Marka_Update(string i_Marka_ID, string i_Row_Status, string i_User_ID, string i_Marka_Name, string i_Code_of_mark, string i_Description_Eng, string i_Description_Rus, string i_Engineering_Drawing_Type_Eng, string i_Engineering_Drawing_Type_Rus, string i_IsUsedInMatrix, string i_IsPriority, string i_ReportColor, string i_ReportOrder, ObjectParameter o_IsError)
        {
            var i_Marka_IDParameter = i_Marka_ID != null ?
                new ObjectParameter("i_Marka_ID", i_Marka_ID) :
                new ObjectParameter("i_Marka_ID", typeof(string));
    
            var i_Row_StatusParameter = i_Row_Status != null ?
                new ObjectParameter("i_Row_Status", i_Row_Status) :
                new ObjectParameter("i_Row_Status", typeof(string));
    
            var i_User_IDParameter = i_User_ID != null ?
                new ObjectParameter("i_User_ID", i_User_ID) :
                new ObjectParameter("i_User_ID", typeof(string));
    
            var i_Marka_NameParameter = i_Marka_Name != null ?
                new ObjectParameter("i_Marka_Name", i_Marka_Name) :
                new ObjectParameter("i_Marka_Name", typeof(string));
    
            var i_Code_of_markParameter = i_Code_of_mark != null ?
                new ObjectParameter("i_Code_of_mark", i_Code_of_mark) :
                new ObjectParameter("i_Code_of_mark", typeof(string));
    
            var i_Description_EngParameter = i_Description_Eng != null ?
                new ObjectParameter("i_Description_Eng", i_Description_Eng) :
                new ObjectParameter("i_Description_Eng", typeof(string));
    
            var i_Description_RusParameter = i_Description_Rus != null ?
                new ObjectParameter("i_Description_Rus", i_Description_Rus) :
                new ObjectParameter("i_Description_Rus", typeof(string));
    
            var i_Engineering_Drawing_Type_EngParameter = i_Engineering_Drawing_Type_Eng != null ?
                new ObjectParameter("i_Engineering_Drawing_Type_Eng", i_Engineering_Drawing_Type_Eng) :
                new ObjectParameter("i_Engineering_Drawing_Type_Eng", typeof(string));
    
            var i_Engineering_Drawing_Type_RusParameter = i_Engineering_Drawing_Type_Rus != null ?
                new ObjectParameter("i_Engineering_Drawing_Type_Rus", i_Engineering_Drawing_Type_Rus) :
                new ObjectParameter("i_Engineering_Drawing_Type_Rus", typeof(string));
    
            var i_IsUsedInMatrixParameter = i_IsUsedInMatrix != null ?
                new ObjectParameter("i_IsUsedInMatrix", i_IsUsedInMatrix) :
                new ObjectParameter("i_IsUsedInMatrix", typeof(string));
    
            var i_IsPriorityParameter = i_IsPriority != null ?
                new ObjectParameter("i_IsPriority", i_IsPriority) :
                new ObjectParameter("i_IsPriority", typeof(string));
    
            var i_ReportColorParameter = i_ReportColor != null ?
                new ObjectParameter("i_ReportColor", i_ReportColor) :
                new ObjectParameter("i_ReportColor", typeof(string));
    
            var i_ReportOrderParameter = i_ReportOrder != null ?
                new ObjectParameter("i_ReportOrder", i_ReportOrder) :
                new ObjectParameter("i_ReportOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Marka_Update_Result>("Marka_Update", i_Marka_IDParameter, i_Row_StatusParameter, i_User_IDParameter, i_Marka_NameParameter, i_Code_of_markParameter, i_Description_EngParameter, i_Description_RusParameter, i_Engineering_Drawing_Type_EngParameter, i_Engineering_Drawing_Type_RusParameter, i_IsUsedInMatrixParameter, i_IsPriorityParameter, i_ReportColorParameter, i_ReportOrderParameter, o_IsError);
        }
    
        public virtual ObjectResult<TitleObject_Delete_Result> TitleObject_Delete(string i_User_ID, string i_TitleObject_ID, ObjectParameter o_IsError)
        {
            var i_User_IDParameter = i_User_ID != null ?
                new ObjectParameter("i_User_ID", i_User_ID) :
                new ObjectParameter("i_User_ID", typeof(string));
    
            var i_TitleObject_IDParameter = i_TitleObject_ID != null ?
                new ObjectParameter("i_TitleObject_ID", i_TitleObject_ID) :
                new ObjectParameter("i_TitleObject_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TitleObject_Delete_Result>("TitleObject_Delete", i_User_IDParameter, i_TitleObject_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<TitleObject_Insert_Result> TitleObject_Insert(string i_Row_Status, string i_User_ID, string i_TitleObject_Name, string i_TitleObject_PARENTID, string i_Structure, string i_Description_Eng, string i_Description_Rus, string i_Phase_Name, string i_ReportColor, string i_ReportOrder, string i_GLB_Weight, string i_Book1_Pct, string i_Book1_Weight, string i_Book2_Pct, string i_Book2_Weight, string i_Book3_Pct, string i_Book3_Weight, string i_Book4_Weight, string i_TitleObject_for_ABDFinalSet, string i_Book1_Documents_Total, string i_Book1_Documents_received, string i_Book1_Progress, string i_Book1_Documents_transmitted_to_CPY, string i_StageOfConstr, ObjectParameter o_Entity_ID, ObjectParameter o_IsError)
        {
            var i_Row_StatusParameter = i_Row_Status != null ?
                new ObjectParameter("i_Row_Status", i_Row_Status) :
                new ObjectParameter("i_Row_Status", typeof(string));
    
            var i_User_IDParameter = i_User_ID != null ?
                new ObjectParameter("i_User_ID", i_User_ID) :
                new ObjectParameter("i_User_ID", typeof(string));
    
            var i_TitleObject_NameParameter = i_TitleObject_Name != null ?
                new ObjectParameter("i_TitleObject_Name", i_TitleObject_Name) :
                new ObjectParameter("i_TitleObject_Name", typeof(string));
    
            var i_TitleObject_PARENTIDParameter = i_TitleObject_PARENTID != null ?
                new ObjectParameter("i_TitleObject_PARENTID", i_TitleObject_PARENTID) :
                new ObjectParameter("i_TitleObject_PARENTID", typeof(string));
    
            var i_StructureParameter = i_Structure != null ?
                new ObjectParameter("i_Structure", i_Structure) :
                new ObjectParameter("i_Structure", typeof(string));
    
            var i_Description_EngParameter = i_Description_Eng != null ?
                new ObjectParameter("i_Description_Eng", i_Description_Eng) :
                new ObjectParameter("i_Description_Eng", typeof(string));
    
            var i_Description_RusParameter = i_Description_Rus != null ?
                new ObjectParameter("i_Description_Rus", i_Description_Rus) :
                new ObjectParameter("i_Description_Rus", typeof(string));
    
            var i_Phase_NameParameter = i_Phase_Name != null ?
                new ObjectParameter("i_Phase_Name", i_Phase_Name) :
                new ObjectParameter("i_Phase_Name", typeof(string));
    
            var i_ReportColorParameter = i_ReportColor != null ?
                new ObjectParameter("i_ReportColor", i_ReportColor) :
                new ObjectParameter("i_ReportColor", typeof(string));
    
            var i_ReportOrderParameter = i_ReportOrder != null ?
                new ObjectParameter("i_ReportOrder", i_ReportOrder) :
                new ObjectParameter("i_ReportOrder", typeof(string));
    
            var i_GLB_WeightParameter = i_GLB_Weight != null ?
                new ObjectParameter("i_GLB_Weight", i_GLB_Weight) :
                new ObjectParameter("i_GLB_Weight", typeof(string));
    
            var i_Book1_PctParameter = i_Book1_Pct != null ?
                new ObjectParameter("i_Book1_Pct", i_Book1_Pct) :
                new ObjectParameter("i_Book1_Pct", typeof(string));
    
            var i_Book1_WeightParameter = i_Book1_Weight != null ?
                new ObjectParameter("i_Book1_Weight", i_Book1_Weight) :
                new ObjectParameter("i_Book1_Weight", typeof(string));
    
            var i_Book2_PctParameter = i_Book2_Pct != null ?
                new ObjectParameter("i_Book2_Pct", i_Book2_Pct) :
                new ObjectParameter("i_Book2_Pct", typeof(string));
    
            var i_Book2_WeightParameter = i_Book2_Weight != null ?
                new ObjectParameter("i_Book2_Weight", i_Book2_Weight) :
                new ObjectParameter("i_Book2_Weight", typeof(string));
    
            var i_Book3_PctParameter = i_Book3_Pct != null ?
                new ObjectParameter("i_Book3_Pct", i_Book3_Pct) :
                new ObjectParameter("i_Book3_Pct", typeof(string));
    
            var i_Book3_WeightParameter = i_Book3_Weight != null ?
                new ObjectParameter("i_Book3_Weight", i_Book3_Weight) :
                new ObjectParameter("i_Book3_Weight", typeof(string));
    
            var i_Book4_WeightParameter = i_Book4_Weight != null ?
                new ObjectParameter("i_Book4_Weight", i_Book4_Weight) :
                new ObjectParameter("i_Book4_Weight", typeof(string));
    
            var i_TitleObject_for_ABDFinalSetParameter = i_TitleObject_for_ABDFinalSet != null ?
                new ObjectParameter("i_TitleObject_for_ABDFinalSet", i_TitleObject_for_ABDFinalSet) :
                new ObjectParameter("i_TitleObject_for_ABDFinalSet", typeof(string));
    
            var i_Book1_Documents_TotalParameter = i_Book1_Documents_Total != null ?
                new ObjectParameter("i_Book1_Documents_Total", i_Book1_Documents_Total) :
                new ObjectParameter("i_Book1_Documents_Total", typeof(string));
    
            var i_Book1_Documents_receivedParameter = i_Book1_Documents_received != null ?
                new ObjectParameter("i_Book1_Documents_received", i_Book1_Documents_received) :
                new ObjectParameter("i_Book1_Documents_received", typeof(string));
    
            var i_Book1_ProgressParameter = i_Book1_Progress != null ?
                new ObjectParameter("i_Book1_Progress", i_Book1_Progress) :
                new ObjectParameter("i_Book1_Progress", typeof(string));
    
            var i_Book1_Documents_transmitted_to_CPYParameter = i_Book1_Documents_transmitted_to_CPY != null ?
                new ObjectParameter("i_Book1_Documents_transmitted_to_CPY", i_Book1_Documents_transmitted_to_CPY) :
                new ObjectParameter("i_Book1_Documents_transmitted_to_CPY", typeof(string));
    
            var i_StageOfConstrParameter = i_StageOfConstr != null ?
                new ObjectParameter("i_StageOfConstr", i_StageOfConstr) :
                new ObjectParameter("i_StageOfConstr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TitleObject_Insert_Result>("TitleObject_Insert", i_Row_StatusParameter, i_User_IDParameter, i_TitleObject_NameParameter, i_TitleObject_PARENTIDParameter, i_StructureParameter, i_Description_EngParameter, i_Description_RusParameter, i_Phase_NameParameter, i_ReportColorParameter, i_ReportOrderParameter, i_GLB_WeightParameter, i_Book1_PctParameter, i_Book1_WeightParameter, i_Book2_PctParameter, i_Book2_WeightParameter, i_Book3_PctParameter, i_Book3_WeightParameter, i_Book4_WeightParameter, i_TitleObject_for_ABDFinalSetParameter, i_Book1_Documents_TotalParameter, i_Book1_Documents_receivedParameter, i_Book1_ProgressParameter, i_Book1_Documents_transmitted_to_CPYParameter, i_StageOfConstrParameter, o_Entity_ID, o_IsError);
        }
    
        public virtual ObjectResult<TitleObject_Update_Result> TitleObject_Update(string i_TitleObject_ID, string i_Row_Status, string i_User_ID, string i_TitleObject_Name, string i_TitleObject_PARENTID, string i_Structure, string i_Description_Eng, string i_Description_Rus, string i_Phase_Name, string i_ReportColor, string i_ReportOrder, string i_GLB_Weight, string i_Book1_Pct, string i_Book1_Weight, string i_Book2_Pct, string i_Book2_Weight, string i_Book3_Pct, string i_Book3_Weight, string i_Book4_Weight, string i_TitleObject_for_ABDFinalSet, string i_Book1_Documents_Total, string i_Book1_Documents_received, string i_Book1_Progress, string i_Book1_Documents_transmitted_to_CPY, string i_StageOfConstr, ObjectParameter o_IsError)
        {
            var i_TitleObject_IDParameter = i_TitleObject_ID != null ?
                new ObjectParameter("i_TitleObject_ID", i_TitleObject_ID) :
                new ObjectParameter("i_TitleObject_ID", typeof(string));
    
            var i_Row_StatusParameter = i_Row_Status != null ?
                new ObjectParameter("i_Row_Status", i_Row_Status) :
                new ObjectParameter("i_Row_Status", typeof(string));
    
            var i_User_IDParameter = i_User_ID != null ?
                new ObjectParameter("i_User_ID", i_User_ID) :
                new ObjectParameter("i_User_ID", typeof(string));
    
            var i_TitleObject_NameParameter = i_TitleObject_Name != null ?
                new ObjectParameter("i_TitleObject_Name", i_TitleObject_Name) :
                new ObjectParameter("i_TitleObject_Name", typeof(string));
    
            var i_TitleObject_PARENTIDParameter = i_TitleObject_PARENTID != null ?
                new ObjectParameter("i_TitleObject_PARENTID", i_TitleObject_PARENTID) :
                new ObjectParameter("i_TitleObject_PARENTID", typeof(string));
    
            var i_StructureParameter = i_Structure != null ?
                new ObjectParameter("i_Structure", i_Structure) :
                new ObjectParameter("i_Structure", typeof(string));
    
            var i_Description_EngParameter = i_Description_Eng != null ?
                new ObjectParameter("i_Description_Eng", i_Description_Eng) :
                new ObjectParameter("i_Description_Eng", typeof(string));
    
            var i_Description_RusParameter = i_Description_Rus != null ?
                new ObjectParameter("i_Description_Rus", i_Description_Rus) :
                new ObjectParameter("i_Description_Rus", typeof(string));
    
            var i_Phase_NameParameter = i_Phase_Name != null ?
                new ObjectParameter("i_Phase_Name", i_Phase_Name) :
                new ObjectParameter("i_Phase_Name", typeof(string));
    
            var i_ReportColorParameter = i_ReportColor != null ?
                new ObjectParameter("i_ReportColor", i_ReportColor) :
                new ObjectParameter("i_ReportColor", typeof(string));
    
            var i_ReportOrderParameter = i_ReportOrder != null ?
                new ObjectParameter("i_ReportOrder", i_ReportOrder) :
                new ObjectParameter("i_ReportOrder", typeof(string));
    
            var i_GLB_WeightParameter = i_GLB_Weight != null ?
                new ObjectParameter("i_GLB_Weight", i_GLB_Weight) :
                new ObjectParameter("i_GLB_Weight", typeof(string));
    
            var i_Book1_PctParameter = i_Book1_Pct != null ?
                new ObjectParameter("i_Book1_Pct", i_Book1_Pct) :
                new ObjectParameter("i_Book1_Pct", typeof(string));
    
            var i_Book1_WeightParameter = i_Book1_Weight != null ?
                new ObjectParameter("i_Book1_Weight", i_Book1_Weight) :
                new ObjectParameter("i_Book1_Weight", typeof(string));
    
            var i_Book2_PctParameter = i_Book2_Pct != null ?
                new ObjectParameter("i_Book2_Pct", i_Book2_Pct) :
                new ObjectParameter("i_Book2_Pct", typeof(string));
    
            var i_Book2_WeightParameter = i_Book2_Weight != null ?
                new ObjectParameter("i_Book2_Weight", i_Book2_Weight) :
                new ObjectParameter("i_Book2_Weight", typeof(string));
    
            var i_Book3_PctParameter = i_Book3_Pct != null ?
                new ObjectParameter("i_Book3_Pct", i_Book3_Pct) :
                new ObjectParameter("i_Book3_Pct", typeof(string));
    
            var i_Book3_WeightParameter = i_Book3_Weight != null ?
                new ObjectParameter("i_Book3_Weight", i_Book3_Weight) :
                new ObjectParameter("i_Book3_Weight", typeof(string));
    
            var i_Book4_WeightParameter = i_Book4_Weight != null ?
                new ObjectParameter("i_Book4_Weight", i_Book4_Weight) :
                new ObjectParameter("i_Book4_Weight", typeof(string));
    
            var i_TitleObject_for_ABDFinalSetParameter = i_TitleObject_for_ABDFinalSet != null ?
                new ObjectParameter("i_TitleObject_for_ABDFinalSet", i_TitleObject_for_ABDFinalSet) :
                new ObjectParameter("i_TitleObject_for_ABDFinalSet", typeof(string));
    
            var i_Book1_Documents_TotalParameter = i_Book1_Documents_Total != null ?
                new ObjectParameter("i_Book1_Documents_Total", i_Book1_Documents_Total) :
                new ObjectParameter("i_Book1_Documents_Total", typeof(string));
    
            var i_Book1_Documents_receivedParameter = i_Book1_Documents_received != null ?
                new ObjectParameter("i_Book1_Documents_received", i_Book1_Documents_received) :
                new ObjectParameter("i_Book1_Documents_received", typeof(string));
    
            var i_Book1_ProgressParameter = i_Book1_Progress != null ?
                new ObjectParameter("i_Book1_Progress", i_Book1_Progress) :
                new ObjectParameter("i_Book1_Progress", typeof(string));
    
            var i_Book1_Documents_transmitted_to_CPYParameter = i_Book1_Documents_transmitted_to_CPY != null ?
                new ObjectParameter("i_Book1_Documents_transmitted_to_CPY", i_Book1_Documents_transmitted_to_CPY) :
                new ObjectParameter("i_Book1_Documents_transmitted_to_CPY", typeof(string));
    
            var i_StageOfConstrParameter = i_StageOfConstr != null ?
                new ObjectParameter("i_StageOfConstr", i_StageOfConstr) :
                new ObjectParameter("i_StageOfConstr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TitleObject_Update_Result>("TitleObject_Update", i_TitleObject_IDParameter, i_Row_StatusParameter, i_User_IDParameter, i_TitleObject_NameParameter, i_TitleObject_PARENTIDParameter, i_StructureParameter, i_Description_EngParameter, i_Description_RusParameter, i_Phase_NameParameter, i_ReportColorParameter, i_ReportOrderParameter, i_GLB_WeightParameter, i_Book1_PctParameter, i_Book1_WeightParameter, i_Book2_PctParameter, i_Book2_WeightParameter, i_Book3_PctParameter, i_Book3_WeightParameter, i_Book4_WeightParameter, i_TitleObject_for_ABDFinalSetParameter, i_Book1_Documents_TotalParameter, i_Book1_Documents_receivedParameter, i_Book1_ProgressParameter, i_Book1_Documents_transmitted_to_CPYParameter, i_StageOfConstrParameter, o_IsError);
        }
    
        public virtual ObjectResult<ABDDocument_Delete_Result> ABDDocument_Delete(string i_User_ID, string i_ABDDocument_ID, ObjectParameter o_IsError)
        {
            var i_User_IDParameter = i_User_ID != null ?
                new ObjectParameter("i_User_ID", i_User_ID) :
                new ObjectParameter("i_User_ID", typeof(string));
    
            var i_ABDDocument_IDParameter = i_ABDDocument_ID != null ?
                new ObjectParameter("i_ABDDocument_ID", i_ABDDocument_ID) :
                new ObjectParameter("i_ABDDocument_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ABDDocument_Delete_Result>("ABDDocument_Delete", i_User_IDParameter, i_ABDDocument_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<ABDDocument_Insert_Result> ABDDocument_Insert(string i_Row_Status, string i_User_ID, string i_ABDDocument_Name, string i_ABDDocument_Number, string i_Issue_Date, string i_Sheet_Folder_Number, string i_Total_Sheets, string i_Number_in_Folder, string i_ABDFinalFolder_Name, ObjectParameter o_Entity_ID, ObjectParameter o_IsError)
        {
            var i_Row_StatusParameter = i_Row_Status != null ?
                new ObjectParameter("i_Row_Status", i_Row_Status) :
                new ObjectParameter("i_Row_Status", typeof(string));
    
            var i_User_IDParameter = i_User_ID != null ?
                new ObjectParameter("i_User_ID", i_User_ID) :
                new ObjectParameter("i_User_ID", typeof(string));
    
            var i_ABDDocument_NameParameter = i_ABDDocument_Name != null ?
                new ObjectParameter("i_ABDDocument_Name", i_ABDDocument_Name) :
                new ObjectParameter("i_ABDDocument_Name", typeof(string));
    
            var i_ABDDocument_NumberParameter = i_ABDDocument_Number != null ?
                new ObjectParameter("i_ABDDocument_Number", i_ABDDocument_Number) :
                new ObjectParameter("i_ABDDocument_Number", typeof(string));
    
            var i_Issue_DateParameter = i_Issue_Date != null ?
                new ObjectParameter("i_Issue_Date", i_Issue_Date) :
                new ObjectParameter("i_Issue_Date", typeof(string));
    
            var i_Sheet_Folder_NumberParameter = i_Sheet_Folder_Number != null ?
                new ObjectParameter("i_Sheet_Folder_Number", i_Sheet_Folder_Number) :
                new ObjectParameter("i_Sheet_Folder_Number", typeof(string));
    
            var i_Total_SheetsParameter = i_Total_Sheets != null ?
                new ObjectParameter("i_Total_Sheets", i_Total_Sheets) :
                new ObjectParameter("i_Total_Sheets", typeof(string));
    
            var i_Number_in_FolderParameter = i_Number_in_Folder != null ?
                new ObjectParameter("i_Number_in_Folder", i_Number_in_Folder) :
                new ObjectParameter("i_Number_in_Folder", typeof(string));
    
            var i_ABDFinalFolder_NameParameter = i_ABDFinalFolder_Name != null ?
                new ObjectParameter("i_ABDFinalFolder_Name", i_ABDFinalFolder_Name) :
                new ObjectParameter("i_ABDFinalFolder_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ABDDocument_Insert_Result>("ABDDocument_Insert", i_Row_StatusParameter, i_User_IDParameter, i_ABDDocument_NameParameter, i_ABDDocument_NumberParameter, i_Issue_DateParameter, i_Sheet_Folder_NumberParameter, i_Total_SheetsParameter, i_Number_in_FolderParameter, i_ABDFinalFolder_NameParameter, o_Entity_ID, o_IsError);
        }
    
        public virtual ObjectResult<ABDDocument_To_FileTable_Stream_Delete_Result> ABDDocument_To_FileTable_Stream_Delete(string i_User_ID, string i_ABDDocument_to_FileTable_Stream_ID, ObjectParameter o_IsError)
        {
            var i_User_IDParameter = i_User_ID != null ?
                new ObjectParameter("i_User_ID", i_User_ID) :
                new ObjectParameter("i_User_ID", typeof(string));
    
            var i_ABDDocument_to_FileTable_Stream_IDParameter = i_ABDDocument_to_FileTable_Stream_ID != null ?
                new ObjectParameter("i_ABDDocument_to_FileTable_Stream_ID", i_ABDDocument_to_FileTable_Stream_ID) :
                new ObjectParameter("i_ABDDocument_to_FileTable_Stream_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ABDDocument_To_FileTable_Stream_Delete_Result>("ABDDocument_To_FileTable_Stream_Delete", i_User_IDParameter, i_ABDDocument_to_FileTable_Stream_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<ABDDocument_to_FileTable_Stream_Insert_Result> ABDDocument_to_FileTable_Stream_Insert(string i_Row_Status, string i_User_ID, string i_ABDDocument_ID, string i_FileTable_Stream_ID, ObjectParameter o_Entity_ID, ObjectParameter o_IsError)
        {
            var i_Row_StatusParameter = i_Row_Status != null ?
                new ObjectParameter("i_Row_Status", i_Row_Status) :
                new ObjectParameter("i_Row_Status", typeof(string));
    
            var i_User_IDParameter = i_User_ID != null ?
                new ObjectParameter("i_User_ID", i_User_ID) :
                new ObjectParameter("i_User_ID", typeof(string));
    
            var i_ABDDocument_IDParameter = i_ABDDocument_ID != null ?
                new ObjectParameter("i_ABDDocument_ID", i_ABDDocument_ID) :
                new ObjectParameter("i_ABDDocument_ID", typeof(string));
    
            var i_FileTable_Stream_IDParameter = i_FileTable_Stream_ID != null ?
                new ObjectParameter("i_FileTable_Stream_ID", i_FileTable_Stream_ID) :
                new ObjectParameter("i_FileTable_Stream_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ABDDocument_to_FileTable_Stream_Insert_Result>("ABDDocument_to_FileTable_Stream_Insert", i_Row_StatusParameter, i_User_IDParameter, i_ABDDocument_IDParameter, i_FileTable_Stream_IDParameter, o_Entity_ID, o_IsError);
        }
    
        public virtual ObjectResult<ABDDocument_to_FileTable_Stream_Update_Result> ABDDocument_to_FileTable_Stream_Update(string i_ABDDocument_to_FileTable_Stream_ID, string i_Row_Status, string i_User_ID, string i_ABDDocument_ID, string i_FileTable_Stream_ID, ObjectParameter o_IsError)
        {
            var i_ABDDocument_to_FileTable_Stream_IDParameter = i_ABDDocument_to_FileTable_Stream_ID != null ?
                new ObjectParameter("i_ABDDocument_to_FileTable_Stream_ID", i_ABDDocument_to_FileTable_Stream_ID) :
                new ObjectParameter("i_ABDDocument_to_FileTable_Stream_ID", typeof(string));
    
            var i_Row_StatusParameter = i_Row_Status != null ?
                new ObjectParameter("i_Row_Status", i_Row_Status) :
                new ObjectParameter("i_Row_Status", typeof(string));
    
            var i_User_IDParameter = i_User_ID != null ?
                new ObjectParameter("i_User_ID", i_User_ID) :
                new ObjectParameter("i_User_ID", typeof(string));
    
            var i_ABDDocument_IDParameter = i_ABDDocument_ID != null ?
                new ObjectParameter("i_ABDDocument_ID", i_ABDDocument_ID) :
                new ObjectParameter("i_ABDDocument_ID", typeof(string));
    
            var i_FileTable_Stream_IDParameter = i_FileTable_Stream_ID != null ?
                new ObjectParameter("i_FileTable_Stream_ID", i_FileTable_Stream_ID) :
                new ObjectParameter("i_FileTable_Stream_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ABDDocument_to_FileTable_Stream_Update_Result>("ABDDocument_to_FileTable_Stream_Update", i_ABDDocument_to_FileTable_Stream_IDParameter, i_Row_StatusParameter, i_User_IDParameter, i_ABDDocument_IDParameter, i_FileTable_Stream_IDParameter, o_IsError);
        }
    
        public virtual ObjectResult<Nullable<long>> Register_SequenceNumber()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("Register_SequenceNumber");
        }
    
        public virtual ObjectResult<ABDDocument_Update_Result> ABDDocument_Update(string i_ABDDocument_ID, string i_Row_Status, string i_User_ID, string i_ABDDocument_Name, string i_ABDDocument_Number, string i_Issue_Date, string i_Sheet_Folder_Number, string i_Total_Sheets, string i_Number_in_Folder, string i_ABDFinalFolder_Name, ObjectParameter o_Entity_ID, ObjectParameter o_IsError)
        {
            var i_ABDDocument_IDParameter = i_ABDDocument_ID != null ?
                new ObjectParameter("i_ABDDocument_ID", i_ABDDocument_ID) :
                new ObjectParameter("i_ABDDocument_ID", typeof(string));
    
            var i_Row_StatusParameter = i_Row_Status != null ?
                new ObjectParameter("i_Row_Status", i_Row_Status) :
                new ObjectParameter("i_Row_Status", typeof(string));
    
            var i_User_IDParameter = i_User_ID != null ?
                new ObjectParameter("i_User_ID", i_User_ID) :
                new ObjectParameter("i_User_ID", typeof(string));
    
            var i_ABDDocument_NameParameter = i_ABDDocument_Name != null ?
                new ObjectParameter("i_ABDDocument_Name", i_ABDDocument_Name) :
                new ObjectParameter("i_ABDDocument_Name", typeof(string));
    
            var i_ABDDocument_NumberParameter = i_ABDDocument_Number != null ?
                new ObjectParameter("i_ABDDocument_Number", i_ABDDocument_Number) :
                new ObjectParameter("i_ABDDocument_Number", typeof(string));
    
            var i_Issue_DateParameter = i_Issue_Date != null ?
                new ObjectParameter("i_Issue_Date", i_Issue_Date) :
                new ObjectParameter("i_Issue_Date", typeof(string));
    
            var i_Sheet_Folder_NumberParameter = i_Sheet_Folder_Number != null ?
                new ObjectParameter("i_Sheet_Folder_Number", i_Sheet_Folder_Number) :
                new ObjectParameter("i_Sheet_Folder_Number", typeof(string));
    
            var i_Total_SheetsParameter = i_Total_Sheets != null ?
                new ObjectParameter("i_Total_Sheets", i_Total_Sheets) :
                new ObjectParameter("i_Total_Sheets", typeof(string));
    
            var i_Number_in_FolderParameter = i_Number_in_Folder != null ?
                new ObjectParameter("i_Number_in_Folder", i_Number_in_Folder) :
                new ObjectParameter("i_Number_in_Folder", typeof(string));
    
            var i_ABDFinalFolder_NameParameter = i_ABDFinalFolder_Name != null ?
                new ObjectParameter("i_ABDFinalFolder_Name", i_ABDFinalFolder_Name) :
                new ObjectParameter("i_ABDFinalFolder_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ABDDocument_Update_Result>("ABDDocument_Update", i_ABDDocument_IDParameter, i_Row_StatusParameter, i_User_IDParameter, i_ABDDocument_NameParameter, i_ABDDocument_NumberParameter, i_Issue_DateParameter, i_Sheet_Folder_NumberParameter, i_Total_SheetsParameter, i_Number_in_FolderParameter, i_ABDFinalFolder_NameParameter, o_Entity_ID, o_IsError);
        }
    }
}
