//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FileStorageEntities : DbContext
    {
        public FileStorageEntities()
            : base("name=FileStorageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FileShareTable> FileShareTables { get; set; }
    
        public virtual ObjectResult<string> Get_RootPath(string fileTable)
        {
            var fileTableParameter = fileTable != null ?
                new ObjectParameter("FileTable", fileTable) :
                new ObjectParameter("FileTable", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Get_RootPath", fileTableParameter);
        }
    
        public virtual ObjectResult<SearchInFiles_Result> SearchInFiles(string searchList, string searchString, ObjectParameter foundList, ObjectParameter o_IsError)
        {
            var searchListParameter = searchList != null ?
                new ObjectParameter("SearchList", searchList) :
                new ObjectParameter("SearchList", typeof(string));
    
            var searchStringParameter = searchString != null ?
                new ObjectParameter("SearchString", searchString) :
                new ObjectParameter("SearchString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchInFiles_Result>("SearchInFiles", searchListParameter, searchStringParameter, foundList, o_IsError);
        }
    }
}
