//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UI_ISO
    {
        public System.Guid ISO_ID { get; set; }
        public string ISO_Number { get; set; }
        public Nullable<System.Guid> Marka_ID { get; set; }
        public string Marka_Name { get; set; }
        public Nullable<System.Guid> TitleObject_ID { get; set; }
        public string TitleObject_Name { get; set; }
        public Nullable<System.Guid> DesignAreaType_ID { get; set; }
        public string DesignAreaType_Name { get; set; }
        public Nullable<System.Guid> ProcessPhase_ID { get; set; }
        public string ProcessPhase_Name { get; set; }
        public Nullable<System.Guid> Line_ID { get; set; }
        public Nullable<int> Row_status { get; set; }
        public string Line_Number { get; set; }
        public Nullable<System.Guid> Phase_ID { get; set; }
        public string Phase_Name { get; set; }
        public Nullable<int> Line_Row_status { get; set; }
    }
}
