//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UI_Line
    {
        public System.Guid Line_ID { get; set; }
        public string Line_Number { get; set; }
        public Nullable<int> Row_Status { get; set; }
        public string Location_From { get; set; }
        public string Location_To { get; set; }
        public string Fluid_Name_Eng { get; set; }
        public string Fluid_Name_Rus { get; set; }
        public string Fluid_Danger_Code_By_Gost { get; set; }
        public string Fluid_Fire_Aand_Explosive_Hazard { get; set; }
        public string Fluid_Group_By_TP_TC_032_2013 { get; set; }
        public string Fluid_Group_By_GOST { get; set; }
        public string Pipeline_Category_By_GOST { get; set; }
        public string Piprline_Category_By_TP_TC_032_2013 { get; set; }
    }
}
