//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartQA1._1._2.DB.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UI_RegisterList
    {
        public System.Guid Register_ID { get; set; }
        public string LOG_ID { get; set; }
        public string Register_Number { get; set; }
        public string Phase { get; set; }
        public string TitleObject_Name { get; set; }
        public string Target__Unit_ISO_ { get; set; }
        public string Marka_Name { get; set; }
        public string Work_Desc { get; set; }
        public Nullable<System.DateTime> CNT_Date { get; set; }
        public string SCTR_RESP { get; set; }
        public string CTR_RESP { get; set; }
        public Nullable<System.DateTime> ABDStatusDate { get; set; }
        public string Description_Rus { get; set; }
        public string Notes { get; set; }
        public string TitleColor { get; set; }
        public Nullable<int> TitleOrder { get; set; }
        public string MarkaColor { get; set; }
        public Nullable<int> MarkaOrder { get; set; }
        public string StatusColor { get; set; }
        public Nullable<int> StatusOrder { get; set; }
        public Nullable<System.Guid> TitleObject_ID { get; set; }
        public Nullable<System.Guid> Marka_ID { get; set; }
        public Nullable<System.Guid> ABDStatus_ID { get; set; }
        public Nullable<System.Guid> WorkPackage_ID { get; set; }
        public string WorkPackage_Name { get; set; }
        public Nullable<System.Guid> ProcessPhase_ID { get; set; }
        public string ProcessPhase_Name { get; set; }
        public Nullable<int> Register_Row_status { get; set; }
        public Nullable<int> Register_to_TitleObject_Row_status { get; set; }
        public Nullable<int> Register_to_Marka_Row_status { get; set; }
        public Nullable<System.Guid> Register_to_TitleObject_ID { get; set; }
        public Nullable<System.Guid> Register_to_Marka_ID { get; set; }
        public System.Guid newGuid { get; set; }
        public string FileLOG { get; set; }
        public System.Guid User_Id { get; set; }
    }
}
